# Generated by Django 5.1.5 on 2026-08-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlicuotaIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Cód. Alícuota ARCA')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alícuota %')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Alícuota de IVA',
                'verbose_name_plural': 'Alícuotas de IVA',
                'db_table': 'cble_alicuotas_iva',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('asiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_diario', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Número en Diario')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('condic', models.IntegerField(default=1, verbose_name='Condición Asiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total')),
                ('modulo', models.IntegerField(default=1, verbose_name='Módulo Origen')),
                ('fec_vto', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('fec_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'db_table': 'cble_asiento_enc',
            },
        ),
        migrations.CreateModel(
            name='AsientoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('leyenda', models.CharField(blank=True, max_length=200, verbose_name='Leyenda')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Haber')),
                ('divisa', models.CharField(default='PES', max_length=3, verbose_name='Divisa')),
                ('cotizacion', models.DecimalField(decimal_places=4, default=1.0, max_digits=15, verbose_name='Cotización')),
                ('debe_divisa', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debe Divisa')),
                ('haber_divisa', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Haber Divisa')),
                ('fec_vto', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
            ],
            options={
                'verbose_name': 'Línea de Asiento',
                'verbose_name_plural': 'Líneas de Asiento',
                'db_table': 'cble_asiento_mov',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Código (Legacy)')),
                ('jerarquia', models.CharField(db_index=True, max_length=20, verbose_name='Jerarquía')),
                ('cuenta', models.CharField(db_index=True, max_length=50, verbose_name='Nombre de la Cuenta')),
                ('imputable', models.IntegerField(choices=[(0, 'No imputable'), (1, 'Imputable')], default=0, verbose_name='Imputable')),
                ('tipo', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('N', 'Patrimonio Neto'), ('R', 'Resultado')], max_length=1, verbose_name='Tipo de Cuenta')),
                ('rg_830', models.IntegerField(blank=True, help_text='relacionado con la tabla de rg_830_ret_gcias', null=True, verbose_name='RG 830 (Ret. Ganancias)')),
                ('id_pre', models.IntegerField(blank=True, null=True)),
                ('id_bce', models.IntegerField(blank=True, null=True)),
                ('id_ec', models.IntegerField(blank=True, null=True)),
                ('id_fc', models.IntegerField(blank=True, null=True)),
                ('tipo_disponibilidad', models.CharField(blank=True, choices=[('EFE', 'Efectivo'), ('DOL', 'Dólares'), ('VAL', 'Valores en Cartera'), ('BCO', 'Banco'), ('TAR', 'Tarjetas'), ('OTR', 'Otros')], db_index=True, default='', max_length=3, verbose_name='Tipo de Disponibilidad (Caja Diaria)')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'cble_cuentas',
            },
        ),
        migrations.CreateModel(
            name='LibroIvaAlic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_id', models.IntegerField(db_index=True, verbose_name='ID Asiento Contable')),
                ('c_v', models.CharField(choices=[('C', 'Compras'), ('V', 'Ventas')], db_index=True, max_length=1)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('alicuota', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('computable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('codiva', models.CharField(blank=True, max_length=4, verbose_name='Cód. Alícuota / Comprobante ARCA')),
            ],
            options={
                'verbose_name': 'Alícuota Libro IVA',
                'verbose_name_plural': 'Alícuotas Libro IVA',
                'db_table': 'cble_libro_iva_alic',
            },
        ),
        migrations.CreateModel(
            name='LibroIvaCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_id', models.IntegerField(db_index=True, verbose_name='ID Asiento Contable')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('periodo', models.CharField(blank=True, db_index=True, default='', max_length=6, verbose_name='Período YYYYMM')),
                ('codiva', models.CharField(max_length=3, verbose_name='Cód. Comprobante ARCA')),
                ('punto', models.IntegerField(default=0, verbose_name='Punto de Venta')),
                ('numero', models.BigIntegerField(verbose_name='Número')),
                ('cuit', models.CharField(blank=True, max_length=11, verbose_name='CUIT')),
                ('cae', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='CAE / CAI ARCA')),
                ('neto_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('no_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA Total')),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Otros (ret/perc)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Libro IVA Compras',
                'verbose_name_plural': 'Libro IVA Compras',
                'db_table': 'cble_libro_iva_compras',
            },
        ),
        migrations.CreateModel(
            name='LibroIvaVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_id', models.IntegerField(db_index=True, verbose_name='ID Asiento Contable')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('periodo', models.CharField(blank=True, db_index=True, default='', max_length=6, verbose_name='Período YYYYMM')),
                ('codiva', models.CharField(max_length=3, verbose_name='Cód. Comprobante ARCA')),
                ('punto', models.IntegerField(default=0, verbose_name='Punto de Venta')),
                ('numero', models.BigIntegerField(verbose_name='Número')),
                ('cuit', models.CharField(blank=True, max_length=11, verbose_name='CUIT')),
                ('cae', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='CAE / CAI ARCA')),
                ('neto_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('no_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA Total')),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Otros (ret/perc)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vto_cae', models.DateField(blank=True, null=True, verbose_name='Vto. CAE')),
                ('codigo_qr', models.TextField(blank=True, verbose_name='Código QR')),
            ],
            options={
                'verbose_name': 'Libro IVA Ventas',
                'verbose_name_plural': 'Libro IVA Ventas',
                'db_table': 'cble_libro_iva_ventas',
            },
        ),
    ]
