# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contable', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosContables',
            fields=[
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empresas.empresa', verbose_name='Empresa')),
                ('metodo_contabilizacion_ventas', models.IntegerField(choices=[(1, 'Individual (Por Comprobante)'), (2, 'Consolidado (Resumen Diario por Sucursal)')], default=1, help_text='Establece si se genera un asiento individual por cada ticket o un único asiento diario consolidado', verbose_name='Método Contabilización Ventas')),
            ],
            options={
                'verbose_name': 'Parámetros Contables',
                'verbose_name_plural': 'Parámetros Contables',
                'db_table': 'cble_parametros',
            },
        ),
        migrations.CreateModel(
            name='RetencionPracticada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.CharField(choices=[('IVA', 'IVA'), ('GAN', 'Ganancias'), ('IIBB', 'Ingresos Brutos'), ('TEM', 'Tasa Específica / TEM'), ('SIRCREB', 'SIRCREB'), ('SUSS', 'SUSS'), ('MUN', 'Municipal'), ('OTRO', 'Otro')], db_index=True, default='GAN', max_length=10)),
                ('regimen', models.CharField(blank=True, help_text='Código de régimen ARCA (RG 830). Se sugiere desde la cuenta imputada en las facturas pagadas.', max_length=10, verbose_name='Régimen')),
                ('nro_certificado', models.CharField(blank=True, max_length=30, verbose_name='Nro. Certificado')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha del Certificado')),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Base imponible')),
                ('alicuota', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Alícuota %')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Importe Retenido')),
                ('cuit_retenido', models.CharField(blank=True, max_length=20, verbose_name='CUIT del Retenido')),
                ('asiento_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Asiento Contable')),
            ],
            options={
                'verbose_name': 'Retención Practicada',
                'verbose_name_plural': 'Retenciones Practicadas',
                'db_table': 'cble_retencion_practicada',
            },
        ),
        migrations.CreateModel(
            name='RetPercSufrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_id', models.IntegerField(db_index=True, verbose_name='ID Asiento Contable')),
                ('origen', models.CharField(choices=[('C', 'Compra'), ('V', 'Venta'), ('R', 'Recibo'), ('OP', 'Orden de Pago')], db_index=True, max_length=2)),
                ('tipo', models.CharField(choices=[('R', 'Retención'), ('P', 'Percepción')], max_length=1)),
                ('impuesto', models.CharField(choices=[('IVA', 'IVA'), ('GAN', 'Ganancias'), ('IIBB', 'Ingresos Brutos'), ('TEM', 'Tasa Específica / TEM'), ('SIRCREB', 'SIRCREB'), ('SUSS', 'SUSS'), ('MUN', 'Municipal'), ('OTRO', 'Otro')], db_index=True, max_length=10)),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Base imponible')),
                ('alicuota', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nro_certificado', models.CharField(blank=True, max_length=30, verbose_name='Nro. Certificado')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Certificado')),
                ('cuit_agente', models.CharField(blank=True, max_length=11, verbose_name='CUIT Agente')),
                ('razon_social_agente', models.CharField(blank=True, max_length=200, verbose_name='Razón Social Agente')),
                ('regimen', models.CharField(blank=True, help_text='Código de régimen ARCA/DGR', max_length=10, verbose_name='Régimen')),
            ],
            options={
                'verbose_name': 'Retención/Percepción Sufrida',
                'verbose_name_plural': 'Retenciones/Percepciones Sufridas',
                'db_table': 'cble_ret_perc_sufrida',
            },
        ),
    ]
