# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contable', '0002_initial'),
        ('empresas', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('tesoreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='cli_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.clienteproveedor', verbose_name='Cliente/Proveedor'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asiento',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.ejercicio', verbose_name='Ejercicio Fiscal'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asiento',
            name='sesion_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='tesoreria.cajasesion', verbose_name='Caja de Tesorería'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='asientolinea',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contable.asiento', verbose_name='Asiento'),
        ),
        migrations.AddField(
            model_name='asientolinea',
            name='cli_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.clienteproveedor', verbose_name='Cliente/Proveedor Auxiliar'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='sumariza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='contable.cuenta', verbose_name='Sumariza en'),
        ),
        migrations.AddField(
            model_name='asientolinea',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contable.cuenta', verbose_name='Cuenta Contable'),
        ),
        migrations.AddField(
            model_name='libroivacompras',
            name='clienteproveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.clienteproveedor', verbose_name='Cliente/Proveedor'),
        ),
        migrations.AddField(
            model_name='libroivacompras',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='libroivaventas',
            name='clienteproveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.clienteproveedor', verbose_name='Cliente/Proveedor'),
        ),
        migrations.AddField(
            model_name='libroivaventas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_bonificaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Bonificaciones'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Caja Principal'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_caja_central',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Caja Central (Tesorería)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_caja_central_dolares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Caja Central Dólares'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_caja_mostrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Caja Mostrador'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_caja_mostrador_dolares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Caja Mostrador Dólares'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_caja_reparto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Caja de Reparto (Distribución)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_clientes_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Deudores por Ventas (Default)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Compras (Default)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_descuentos_obtenidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Descuentos Obtenidos (compras)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_diferencia_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Diferencias de Caja (Patrimonial)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_dolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Caja Dólares'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_impuestos_internos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Impuestos Internos'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_itc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. ITC Combustibles'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_iva_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. IVA Crédito (compras)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_iva_debito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. IVA Débito (ventas)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_proveedores_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Proveedores (Default)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_resultado_ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Resultado del Ejercicio'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ret_ganancias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Retención Ganancias (sufrida)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ret_iibb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Retención IIBB (sufrida)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ret_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Retención IVA (sufrida)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ret_mun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Retención Municipal (sufrida)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ret_practicada_ganancias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Retenciones Practicadas Ganancias (RG 830)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ret_practicada_iibb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Retenciones Practicadas IIBB'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ret_practicada_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Retenciones Practicadas IVA'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ret_practicada_suss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Retenciones Practicadas SUSS'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ret_suss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Retención SUSS (sufrida)'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_tarjetas_a_cobrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Tarjetas a Cobrar'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_transferencias_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Transferencias entre Sucursales'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_valores_cartera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Valores a Depositar'),
        ),
        migrations.AddField(
            model_name='parametroscontables',
            name='cta_ventas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cta. Ventas (Default)'),
        ),
        migrations.AddField(
            model_name='retencionpracticada',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='retencionpracticada',
            name='orden_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones_practicadas', to='tesoreria.ordenpago', verbose_name='Orden de Pago'),
        ),
        migrations.AddField(
            model_name='retencionpracticada',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.clienteproveedor', verbose_name='Proveedor Retenido'),
        ),
        migrations.AddField(
            model_name='retpercsufrida',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='retpercsufrida',
            name='jurisdiccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.jurisdiccion', verbose_name='Jurisdicción'),
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['empresa', 'ejercicio', 'fecha'], name='cble_asient_empresa_10c781_idx'),
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['empresa', 'cli_pro'], name='cble_asient_empresa_473846_idx'),
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['sesion_caja', 'asiento_id'], name='idx_asiento_caja'),
        ),
        migrations.AddConstraint(
            model_name='asientolinea',
            constraint=models.CheckConstraint(condition=models.Q(('debe__gte', 0), ('haber__gte', 0)), name='debe_haber_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='asientolinea',
            constraint=models.CheckConstraint(condition=models.Q(('debe__gt', 0), ('haber__gt', 0), _negated=True), name='debe_xor_haber'),
        ),
        migrations.AddIndex(
            model_name='libroivacompras',
            index=models.Index(fields=['empresa', 'fecha'], name='cble_libro__empresa_7905c2_idx'),
        ),
        migrations.AddIndex(
            model_name='libroivacompras',
            index=models.Index(fields=['asiento_id'], name='cble_libro__asiento_3c2842_idx'),
        ),
        migrations.AddIndex(
            model_name='libroivaventas',
            index=models.Index(fields=['empresa', 'fecha'], name='cble_libro__empresa_833cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='libroivaventas',
            index=models.Index(fields=['asiento_id'], name='cble_libro__asiento_f59290_idx'),
        ),
        migrations.AddIndex(
            model_name='retencionpracticada',
            index=models.Index(fields=['empresa', 'fecha'], name='cble_retenc_empresa_b11c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='retencionpracticada',
            index=models.Index(fields=['empresa', 'impuesto'], name='cble_retenc_empresa_f6ef8b_idx'),
        ),
        migrations.AddIndex(
            model_name='retpercsufrida',
            index=models.Index(fields=['empresa', 'fecha'], name='cble_ret_pe_empresa_63d3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='retpercsufrida',
            index=models.Index(fields=['asiento_id'], name='cble_ret_pe_asiento_d3ffd7_idx'),
        ),
        migrations.AddIndex(
            model_name='retpercsufrida',
            index=models.Index(fields=['empresa', 'impuesto'], name='cble_ret_pe_empresa_272633_idx'),
        ),
    ]
