# Generated by Django 5.1.5 on 2026-09-06 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contable', '0003_initial'),
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('facturacion', '0002_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tarifa_f', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tarifa Fiscal (Condic=1)')),
                ('tarifa_p', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tarifa Gestión (Condic=2)')),
                ('activo', models.BooleanField(default=True, verbose_name='Tarifa Activa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_estudio', to='facturacion.clienteproveedor', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contable.cuenta', verbose_name='Cuenta Contable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Servicio/Producto')),
            ],
            options={
                'verbose_name': 'Tarifa de Estudio',
                'verbose_name_plural': 'Tarifas de Estudio',
                'db_table': 'facturacion_tarifaestudio',
            },
        ),
    ]
