# Generated by Django 6.0.4 on 2026-09-28 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_cotizacionmoneda_dolar_cobranza_editable'),
        ('estudio', '0001_initial'),
        ('facturacion', '0005_clienteproveedor_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioFacturaEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(db_index=True, max_length=6, verbose_name='Período Facturado (YYYYMM)')),
                ('destinatarios', models.CharField(blank=True, default='', max_length=500, verbose_name='Destinatarios (Mails)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado de Envío')),
                ('respuesta_smtp', models.TextField(blank=True, null=True, verbose_name='Respuesta SMTP / Registro')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Envío')),
                ('intentos', models.PositiveIntegerField(default=0, verbose_name='Intentos de Envío')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_facturas_estudio', to='facturacion.clienteproveedor', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_facturas_estudio', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio_estudio', to='facturacion.venta', verbose_name='Factura/Comprobante')),
            ],
            options={
                'verbose_name': 'Envío de Factura Estudio',
                'verbose_name_plural': 'Envíos de Facturas Estudio',
                'db_table': 'estudio_envio_factura',
                'indexes': [models.Index(fields=['empresa', 'estado'], name='estudio_env_empresa_4f69a7_idx'), models.Index(fields=['empresa', 'periodo'], name='estudio_env_empresa_267571_idx')],
            },
        ),
    ]
