# Generated by Django 6.0.4 on 2026-10-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0002_enviofacturaestudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviofacturaestudio',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='estudio/facturas_adjuntas/', verbose_name='Comprobante Adjunto Externo'),
        ),
        migrations.AddField(
            model_name='enviofacturaestudio',
            name='modo_adjunto',
            field=models.CharField(choices=[('SISTEMA', 'Usar Factura del Sistema'), ('REEMPLAZAR', 'Intercambiar por Factura Cargada'), ('AMBOS', 'Enviar Agregadas (Sistema + Cargada)')], default='SISTEMA', max_length=20, verbose_name='Modo de Adjuntos'),
        ),
    ]
