# Generated by Django 5.1.5 on 2026-10-01 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_cotizacionmoneda_dolar_cobranza_editable'),
        ('estudio', '0003_enviofacturaestudio_archivo_adjunto_and_more'),
        ('facturacion', '0006_clienteproveedor_facturacion_empresa_bfa3eb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEnvioEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Grupo')),
                ('destinatarios', models.CharField(blank=True, default='', max_length=500, verbose_name='Destinatarios (Mails)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('clientes', models.ManyToManyField(blank=True, related_name='grupos_envio_estudio', to='facturacion.clienteproveedor', verbose_name='Clientes Asociados')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_envio_estudio', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Envío Estudio',
                'verbose_name_plural': 'Grupos de Envío Estudio',
                'db_table': 'estudio_grupo_envio',
            },
        ),
        migrations.AddField(
            model_name='enviofacturaestudio',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_facturas', to='estudio.grupoenvioestudio', verbose_name='Grupo de Envío'),
        ),
        migrations.AddIndex(
            model_name='enviofacturaestudio',
            index=models.Index(fields=['empresa', 'grupo'], name='estudio_env_empresa_c5c0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoenvioestudio',
            index=models.Index(fields=['empresa', 'activo'], name='estudio_gru_empresa_b623df_idx'),
        ),
    ]
