# Generated by Django 5.2.7 on 2026-09-17 00:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contable', '0003_initial'),
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('productos', '0004_alter_producto_unidad_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoMapeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('patron', models.CharField(help_text='Texto clave a buscar en la línea de deducción del PDF (ej. FLETE, COMISION, SELLADO, MERCADERIA EN FINAL)', max_length=100, verbose_name='Patrón / Palabra Clave')),
                ('descripcion', models.CharField(help_text='Descripción legible para el usuario (ej. Fletes de Granos, Comisión Acopio, Impuesto de Sellos)', max_length=150, verbose_name='Descripción del Concepto')),
                ('alicuota_sugerida', models.DecimalField(decimal_places=2, default=Decimal('10.50'), help_text='Alícuota de IVA por defecto para este gasto si el comprobante no la especifica', max_digits=5, verbose_name='Alícuota IVA Sugerida (%)')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cta_gasto', models.ForeignKey(help_text='Cuenta de resultado negativo / pérdida donde se imputa la deducción', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cuenta Contable de Gasto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agricola_gastos_mapeos', to='empresas.empresa', verbose_name='Empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapeo de Gasto de Liquidación',
                'verbose_name_plural': 'Mapeos de Gastos de Liquidaciones',
                'db_table': 'agricola_gasto_mapeo',
                'ordering': ['patron'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'patron'), name='agro_gasto_mapeo_unico_por_empresa')],
            },
        ),
        migrations.CreateModel(
            name='GranoMapeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo_arca', models.IntegerField(help_text='Código oficial de ARCA (ej. 19 para Maíz, 23 para Soja, 15 para Trigo)', verbose_name='Cód. Grano ARCA')),
                ('descripcion_arca', models.CharField(help_text='Denominación oficial del cultivo en ARCA (ej. MAIZ, SOJA, TRIGO PAN)', max_length=100, verbose_name='Descripción ARCA')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cta_ventas', models.ForeignKey(help_text='Cuenta contable de resultado positivo donde se imputa la venta del cultivo (ej. 51 Venta de Soja)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cuenta Contable de Ventas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agricola_granos_mapeos', to='empresas.empresa', verbose_name='Empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeos_granos_arca', to='productos.producto', verbose_name='Producto ERP')),
            ],
            options={
                'verbose_name': 'Mapeo de Grano ARCA',
                'verbose_name_plural': 'Mapeos de Granos ARCA',
                'db_table': 'agricola_grano_mapeo',
                'ordering': ['codigo_arca'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo_arca'), name='agro_grano_mapeo_unico_por_empresa')],
            },
        ),
    ]
