# Generated by Django 5.1.5 on 2026-08-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto', models.IntegerField(verbose_name='Punto')),
                ('tipo_documento', models.CharField(choices=[('ORDEN_COMPRA', 'Orden de Compra'), ('INFORME_RECEPCION', 'Informe de Recepción'), ('REMITO_INTERNO', 'Remito Interno'), ('PEDIDO', 'Pedido de Cliente'), ('REPARTO', 'Reparto / Hoja de Ruta'), ('RECEPCION_DEVOLUCION', 'Recepcion de Devoluciones'), ('VENTA_PRE', 'Presupuesto / PRE (no fiscal)'), ('VENTA_NCI', 'Nota de Crédito Interna (no fiscal)'), ('VENTA_FISCAL', 'Serie fiscal (espejo local / modo prueba)')], max_length=30, verbose_name='Tipo de Documento')),
                ('ultimo_numero', models.BigIntegerField(default=0, verbose_name='Último Número Asignado')),
            ],
            options={
                'verbose_name': 'Contador de Documento',
                'verbose_name_plural': 'Contadores de Documentos',
            },
        ),
    ]
