# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadordocumento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contadores', to='empresas.empresa'),
        ),
        migrations.AddIndex(
            model_name='contadordocumento',
            index=models.Index(fields=['empresa', 'punto', 'tipo_documento'], name='core_contad_empresa_1ddede_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contadordocumento',
            unique_together={('empresa', 'punto', 'tipo_documento')},
        ),
    ]
