# Generated by Django 5.1.5 on 2026-09-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadordocumento',
            name='tipo_documento',
            field=models.CharField(choices=[('ORDEN_COMPRA', 'Orden de Compra'), ('INFORME_RECEPCION', 'Informe de Recepción'), ('REMITO_INTERNO', 'Remito Interno'), ('PEDIDO', 'Pedido de Cliente'), ('REPARTO', 'Reparto / Hoja de Ruta'), ('RECEPCION_DEVOLUCION', 'Recepcion de Devoluciones'), ('VENTA_PRE', 'Presupuesto / PRE (no fiscal)'), ('VENTA_NCI', 'Nota de Crédito Interna (no fiscal)'), ('VENTA_FISCAL', 'Serie fiscal (espejo local / modo prueba)'), ('ROMANEO_TABACO', 'Romaneo de Tabaco')], max_length=30, verbose_name='Tipo de Documento'),
        ),
    ]
