# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcaMisComprobantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('C', 'Compras (Comprobantes Recibidos)'), ('V', 'Ventas (Comprobantes Emitidos)')], db_index=True, max_length=1, verbose_name='Origen (C=Compras, V=Ventas)')),
                ('periodo', models.CharField(db_index=True, max_length=6, verbose_name='Período YYYYMM')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha Comprobante')),
                ('codiva', models.CharField(db_index=True, max_length=3, verbose_name='Código Comprobante ARCA')),
                ('punto', models.IntegerField(verbose_name='Punto de Venta')),
                ('numero', models.BigIntegerField(verbose_name='Número Comprobante')),
                ('numero_hasta', models.BigIntegerField(blank=True, null=True, verbose_name='Número Hasta')),
                ('cuit_contraparte', models.CharField(db_index=True, max_length=11, verbose_name='CUIT Emisor/Receptor')),
                ('razon_social_contraparte', models.CharField(blank=True, max_length=200, verbose_name='Denominación Emisor/Receptor')),
                ('tipo_doc_contraparte', models.CharField(blank=True, max_length=10)),
                ('nro_doc_contraparte', models.CharField(blank=True, max_length=20)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('moneda', models.CharField(default='PES', max_length=5)),
                ('neto_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('no_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cae', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='CAE / CAI ARCA')),
                ('asiento_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Asiento Sistema (Conciliado)')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_comprobantes_arca', to='empresas.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mis Comprobantes ARCA',
                'verbose_name_plural': 'Mis Comprobantes ARCA',
                'db_table': 'arca_mis_comprobantes',
                'indexes': [models.Index(fields=['empresa', 'origen', 'periodo'], name='arca_mis_co_empresa_03fc0b_idx'), models.Index(fields=['empresa', 'asiento_id'], name='arca_mis_co_empresa_5630dc_idx'), models.Index(fields=['cae'], name='arca_mis_co_cae_77217f_idx')],
                'unique_together': {('empresa', 'origen', 'codiva', 'punto', 'numero', 'cuit_contraparte')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=6, verbose_name='Período YYYYMM')),
                ('estado', models.CharField(choices=[('CERRADO', 'Cerrado'), ('ABIERTO', 'Abierto')], db_index=True, default='CERRADO', max_length=10)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora Cierre')),
                ('debito_fiscal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Débito Fiscal (Ventas)')),
                ('credito_fiscal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Crédito Fiscal (Compras)')),
                ('saldo_resultante', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Resultante')),
                ('fecha_reapertura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Reapertura')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_iva', to='empresas.empresa', verbose_name='Empresa')),
                ('usuario_cierre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_iva_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Cierre')),
                ('usuario_reapertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_iva_reabiertos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Reapertura')),
            ],
            options={
                'verbose_name': 'Período IVA',
                'verbose_name_plural': 'Períodos IVA',
                'db_table': 'impuestos_periodo_iva',
                'indexes': [models.Index(fields=['empresa', 'periodo'], name='impuestos_p_empresa_796fe8_idx'), models.Index(fields=['empresa', 'estado'], name='impuestos_p_empresa_a72765_idx')],
                'unique_together': {('empresa', 'periodo')},
            },
        ),
    ]
