# Generated by Django 5.1.5 on 2026-09-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0004_alter_empresa_tipo_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaVertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hace_tabaco', models.BooleanField(default=False, verbose_name='Tabaco')),
                ('hace_granos', models.BooleanField(default=False, verbose_name='Granos (Soja, Maíz, Poroto, etc.)')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agricola_vertical', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuración Agrícola',
                'verbose_name_plural': 'Configuraciones Agrícolas',
                'db_table': 'agricola_empresa_vertical',
            },
        ),
    ]
