# Generated by Django 5.1.5 on 2026-09-06 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agricola', '0001_initial'),
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('detalle', models.CharField(max_length=100, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('estado', models.IntegerField(choices=[(1, 'Abierta'), (2, 'Cerrada')], db_index=True, default=1)),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('ejercicio', models.ForeignKey(blank=True, help_text='Sólo referencia: una campaña puede abarcar más de un ejercicio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanias_agricolas', to='empresas.ejercicio', verbose_name='Ejercicio de referencia')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanias_agricolas', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña Agrícola',
                'verbose_name_plural': 'Campañas Agrícolas',
                'db_table': 'agricola_campania',
                'ordering': ['-fecha_inicio', 'codigo'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='agricola_ca_empresa_37779f_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='agro_campania_codigo_unico'), models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='agro_campania_fechas_coherentes')],
            },
        ),
    ]
