# Generated by Django 5.2.7 on 2026-09-27 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agricola', '0002_campania'),
        ('empresas', '0007_cotizacionmoneda_dolar_cobranza_editable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Establecimiento / Finca')),
                ('localidad', models.CharField(blank=True, max_length=100, verbose_name='Localidad')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('superficie_total_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Superficie Total (Ha)')),
                ('es_propia', models.BooleanField(default=True, help_text='Marcar si es propio o desmarcar si es arrendado', verbose_name='Campo Propio')),
                ('arrendatario_titular', models.CharField(blank=True, max_length=150, verbose_name='Titular / Propietario (si es arrendado)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fincas_agricolas', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finca / Establecimiento',
                'verbose_name_plural': 'Fincas / Establecimientos',
                'db_table': 'agricola_finca',
                'ordering': ['codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de Lote/Sección')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Identificación')),
                ('superficie_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Superficie Cultivable (Ha)')),
                ('aptitud_principal', models.CharField(choices=[('TABACO', 'Tabaco'), ('SOJA', 'Soja'), ('MAIZ', 'Maíz'), ('CANA', 'Caña de Azúcar'), ('POROTO', 'Poroto / Legumbres'), ('TRIGO', 'Trigo / Cereales'), ('PASTURA', 'Pastura / Ganadería'), ('MIXTO', 'Mixto / Rotación'), ('DESCANSO', 'En Descanso / Barbecho'), ('OTRO', 'Otro')], default='MIXTO', max_length=20, verbose_name='Aptitud / Cultivo Principal')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones_agricolas', to='empresas.empresa')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='core_agricola.finca', verbose_name='Finca / Establecimiento')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sección / Lote Productivo',
                'verbose_name_plural': 'Secciones / Lotes Productivos',
                'db_table': 'agricola_seccion',
                'ordering': ['finca', 'codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='finca',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='agro_finca_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='seccion',
            constraint=models.UniqueConstraint(fields=('finca', 'codigo'), name='agro_seccion_codigo_unico'),
        ),
    ]
