# Generated by Django 5.1.5 on 2026-09-27 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agricola', '0003_finca_seccion_finca_agro_finca_codigo_unico_and_more'),
        ('empresas', '0007_cotizacionmoneda_dolar_cobranza_editable'),
        ('facturacion', '0005_clienteproveedor_activo'),
        ('productos', '0008_tomainventario_fecha_autorizo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresavertical',
            name='hace_cana',
            field=models.BooleanField(default=False, verbose_name='Caña de Azúcar'),
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cultivo / Variedad')),
                ('tipo', models.CharField(choices=[('GRANO', 'Granos y Cereales (Soja, Maíz, Trigo, etc.)'), ('TABACO', 'Tabaco (Virginia, Burley, Criollo)'), ('CANA', 'Caña de Azúcar'), ('LEGUMBRE', 'Legumbres (Poroto Negro, Alubia, Garbanzo)'), ('FORRAJE', 'Forrajeras y Pasturas'), ('HORTICOLA', 'Hortícola / Frutícola'), ('OTRO', 'Otro Cultivo')], default='GRANO', max_length=20, verbose_name='Tipo de Cultivo')),
                ('ciclo_estimado_dias', models.IntegerField(default=120, verbose_name='Ciclo Estimado (Días)')),
                ('color_identificador', models.CharField(default='#10b981', max_length=20, verbose_name='Color de Identificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultivos_agricolas', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('producto_cosecha', models.ForeignKey(blank=True, help_text='Producto final del catálogo que se incrementa al cosechar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivos_cosechados', to='productos.producto', verbose_name='Producto de Stock Cosechado')),
            ],
            options={
                'verbose_name': 'Cultivo / Variedad',
                'verbose_name_plural': 'Cultivos / Variedades',
                'db_table': 'agricola_cultivo',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LoteCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('superficie_sembrada_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Superficie Sembrada (Ha)')),
                ('fecha_siembra', models.DateField(blank=True, null=True, verbose_name='Fecha de Siembra')),
                ('fecha_cosecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha Estimada')),
                ('fecha_cosecha_real', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha Real')),
                ('rinde_estimado_kg_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rinde Estimado (kg/ha)')),
                ('rinde_obtenido_kg_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rinde Obtenido (kg/ha)')),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('SEMBRADO', 'Sembrado / En Crecimiento'), ('EN_COSECHA', 'En Cosecha'), ('COSECHADO', 'Cosechado / Finalizado'), ('FRACASADO', 'Fracasado / Pérdida')], default='PLANIFICADO', max_length=20, verbose_name='Estado del Lote')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_asignados', to='core_agricola.campania', verbose_name='Campaña')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_sembrados', to='core_agricola.cultivo', verbose_name='Cultivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_campania_agricolas', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanias_asignadas', to='core_agricola.seccion', verbose_name='Sección / Lote')),
            ],
            options={
                'verbose_name': 'Planificación de Lote por Campaña',
                'verbose_name_plural': 'Planificaciones de Lotes por Campaña',
                'db_table': 'agricola_lote_campania',
                'ordering': ['campania', 'seccion__finca', 'seccion'],
            },
        ),
        migrations.CreateModel(
            name='ParteTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField(verbose_name='N° de Parte / Orden')),
                ('fecha', models.DateField(verbose_name='Fecha de Ejecución')),
                ('superficie_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Superficie Trabajada (Ha)')),
                ('responsable', models.CharField(blank=True, max_length=120, verbose_name='Responsable / Capataz')),
                ('maquinaria', models.CharField(blank=True, max_length=120, verbose_name='Maquinaria / Equipo Utilizado')),
                ('costo_servicio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Servicio/Labor ($)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Planificada / Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada / Aplicada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Condiciones climáticas')),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes_trabajo', to='core_agricola.campania', verbose_name='Campaña')),
                ('contratista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores_contratadas', to='facturacion.clienteproveedor', verbose_name='Contratista / Prestador de Servicio')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes_trabajo_agricolas', to='empresas.empresa')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes_trabajo', to='core_agricola.finca', verbose_name='Finca / Establecimiento')),
                ('lote_campania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_trabajo', to='core_agricola.lotecampania', verbose_name='Cultivo Lote Asignado')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes_trabajo', to='core_agricola.seccion', verbose_name='Sección / Lote')),
            ],
            options={
                'verbose_name': 'Parte de Trabajo / Labor',
                'verbose_name_plural': 'Partes de Trabajo / Labores',
                'db_table': 'agricola_parte_trabajo',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ParteTrabajoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis_ha', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Dosis por Ha')),
                ('unidad_medida', models.CharField(default='LTS/HA', max_length=30, verbose_name='Unidad de Medida')),
                ('cantidad_total', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Cantidad Total Aplicada')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Unitario ($)')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo Total Insumo ($)')),
                ('deposito_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos_labores_agricolas', to='empresas.sucursal', verbose_name='Depósito / Galpón Origen')),
                ('parte_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_aplicados', to='core_agricola.partetrabajo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_agricolas', to='productos.producto', verbose_name='Insumo / Agroquímico')),
            ],
            options={
                'verbose_name': 'Insumo Aplicado en Labor',
                'verbose_name_plural': 'Insumos Aplicados en Labores',
                'db_table': 'agricola_parte_trabajo_insumo',
            },
        ),
        migrations.CreateModel(
            name='TipoLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de la Labor')),
                ('categoria', models.CharField(choices=[('PREPARACION', 'Preparación de Suelo / Barbecho'), ('SIEMBRA', 'Siembra / Plantación / Almácigo'), ('PROTECCION', 'Protección / Pulverización / Fitosanitarios'), ('NUTRICION', 'Fertilización y Enmiendas'), ('MANEJO', 'Manejo Cultural / Desflore / Riego / Carpidas'), ('COSECHA', 'Cosecha / Zafra / Corte'), ('TRANSPORTE', 'Transporte y Logística'), ('OTRO', 'Otras Tareas')], default='PROTECCION', max_length=20, verbose_name='Categoría')),
                ('requiere_insumos', models.BooleanField(default=True, verbose_name='Consume Insumos / Agroquímicos')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_labor_agricolas', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Labor Agrícola',
                'verbose_name_plural': 'Tipos de Labores Agrícolas',
                'db_table': 'agricola_tipo_labor',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='tipo_labor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes_trabajo', to='core_agricola.tipolabor', verbose_name='Tipo de Labor'),
        ),
        migrations.AddConstraint(
            model_name='cultivo',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='agro_cultivo_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='tipolabor',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='agro_tipo_labor_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='partetrabajo',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='agro_parte_trabajo_numero_unico'),
        ),
    ]
