# Generated by Django 5.1.5 on 2026-09-27 16:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agricola', '0004_empresavertical_hace_cana_cultivo_lotecampania_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresavertical',
            name='hace_acopio_tabaco',
            field=models.BooleanField(default=False, verbose_name='Acopio de Tabaco'),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='cantidad_surcos',
            field=models.IntegerField(default=0, help_text='Número de surcos intervenidos en la tarea.', verbose_name='Cantidad de Surcos'),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='metros_surco_trabajados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Metros lineales de surco ejecutados en la labor.', max_digits=12, verbose_name='Metros de Surco Trabajados'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='distanciamiento_surco_m',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.60'), help_text='Distancia entre centros de surco (ej. 1.60 m para Caña, 1.20 m para Tabaco).', max_digits=5, verbose_name='Distanciamiento entre Surcos (m)'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='metros_lineales_surco',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Metros totales de surco en el lote (clave para análisis en Caña de Azúcar y Tabaco).', max_digits=12, verbose_name='Metros Lineales de Surco'),
        ),
        migrations.AlterField(
            model_name='empresavertical',
            name='hace_tabaco',
            field=models.BooleanField(default=False, verbose_name='Tabaco (Cultivo)'),
        ),
    ]
