# Generated by Django 5.1.5 on 2026-09-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='banco_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='C├│digo Banco BCRA'),
        ),
    ]
