# Generated by Django 5.1.5 on 2026-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_alter_cuentabancaria_banco_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='ajuste',
            field=models.IntegerField(default=0, help_text='Ej: 100 = 10% Recargo, -100 = 10% Descuento', verbose_name='Ajuste de Precio'),
        ),
    ]
