# Generated by Django 5.2.7 on 2026-09-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_cotizacionmoneda_dolar_cobranza_editable'),
        ('tesoreria', '0003_mediopago_ajuste'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordenpago',
            unique_together={('empresa', 'punto', 'condic', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='recibo',
            unique_together={('empresa', 'punto', 'condic', 'numero')},
        ),
    ]
