# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('facturacion', '0001_initial'),
        ('productos', '0001_initial'),
        ('tesoreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='compraocimputacion',
            name='compra_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones_oc', to='facturacion.compraitem'),
        ),
        migrations.AddField(
            model_name='compraretperc',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retpercs', to='facturacion.compra'),
        ),
        migrations.AddField(
            model_name='compraretperc',
            name='jurisdiccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.jurisdiccion', verbose_name='Jurisdicción'),
        ),
        migrations.AddField(
            model_name='clienteproveedor',
            name='jurisdiccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.jurisdiccion', verbose_name='Provincia/Jurisdicción'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cli_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.clienteproveedor', verbose_name='Cliente/Proveedor'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.compra', verbose_name='Compra Relacionada'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.ejercicio', verbose_name='Ejercicio Fiscal'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='tesoreria.mediopago', verbose_name='Medio de Pago'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='facturacion.clienteproveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='empresas.sucursal'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que acuerda'),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='compraocimputacion',
            name='orden_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_factura', to='facturacion.ordencompraitem'),
        ),
        migrations.AddField(
            model_name='preventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventas', to='facturacion.clienteproveedor'),
        ),
        migrations.AddField(
            model_name='preventa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='preventa',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.sucursal'),
        ),
        migrations.AddField(
            model_name='preventa',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preventaitem',
            name='preventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.preventa'),
        ),
        migrations.AddField(
            model_name='preventaitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='generada_por_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_generadas', to='facturacion.compra'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='facturacion.clienteproveedor'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='empresas.sucursal', verbose_name='Sucursal (destino / stock)'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepcionimputacion',
            name='orden_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_recepcion', to='facturacion.ordencompraitem'),
        ),
        migrations.AddField(
            model_name='recepcionitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='recepcionitem',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.recepcion'),
        ),
        migrations.AddField(
            model_name='recepcionimputacion',
            name='recepcion_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones', to='facturacion.recepcionitem'),
        ),
        migrations.AddField(
            model_name='remitointerno',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remitointerno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remitos_internos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='remitointerno',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remitointerno',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remitos_internos_recibidos', to='empresas.sucursal', verbose_name='Sucursal Destino'),
        ),
        migrations.AddField(
            model_name='remitointerno',
            name='sucursal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remitos_internos_emitidos', to='empresas.sucursal', verbose_name='Sucursal Origen'),
        ),
        migrations.AddField(
            model_name='remitointerno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remitos_internos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remitointernoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='remitointernoitem',
            name='remito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.remitointerno'),
        ),
        migrations.AddField(
            model_name='remitointernoitem',
            name='subproducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos_internos_items', to='productos.subproducto'),
        ),
        migrations.AddField(
            model_name='recepcionimputacion',
            name='remito_interno_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_recepcion', to='facturacion.remitointernoitem'),
        ),
        migrations.AddField(
            model_name='templatefacturaproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_facturas', to='facturacion.clienteproveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipocomprobante'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cajero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.clienteproveedor'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.ejercicio', verbose_name='Ejercicio Fiscal'),
        ),
        migrations.AddField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.sucursal'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipocomprobante'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cargadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='venta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='facturacion.venta', verbose_name='Comprobante acreditado'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.venta', verbose_name='Venta Relacionada'),
        ),
        migrations.AddField(
            model_name='ventaalicuotaiva',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alicuotas_iva', to='facturacion.venta'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.venta'),
        ),
        migrations.AddIndex(
            model_name='clienteproveedor',
            index=models.Index(fields=['empresa', 'razon_social'], name='facturacion_empresa_793f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='clienteproveedor',
            index=models.Index(fields=['empresa', 'tipo_entidad'], name='facturacion_empresa_abbe64_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'proveedor'], name='facturacion_empresa_925ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'fecha'], name='facturacion_empresa_0cefa4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'estado'], name='facturacion_empresa_29a4ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'punto', 'numero'), name='uq_ordencompra_empresa_punto_numero'),
        ),
        migrations.AddIndex(
            model_name='ordencompraitem',
            index=models.Index(fields=['orden', 'producto'], name='facturacion_orden_i_ae84c9_idx'),
        ),
        migrations.AddIndex(
            model_name='compraocimputacion',
            index=models.Index(fields=['orden_item'], name='facturacion_orden_i_81d211_idx'),
        ),
        migrations.AddIndex(
            model_name='preventa',
            index=models.Index(fields=['empresa', 'fecha'], name='facturacion_empresa_2e341d_idx'),
        ),
        migrations.AddIndex(
            model_name='preventa',
            index=models.Index(fields=['empresa', 'estado'], name='facturacion_empresa_9c4aba_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcion',
            index=models.Index(fields=['empresa', 'fecha'], name='facturacion_empresa_4d09d7_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcion',
            index=models.Index(fields=['empresa', 'proveedor'], name='facturacion_empresa_1549e5_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcion',
            index=models.Index(fields=['empresa', 'origen'], name='facturacion_empresa_f64d4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='recepcion',
            constraint=models.UniqueConstraint(fields=('empresa', 'punto', 'numero'), name='uq_recepcion_empresa_punto_numero'),
        ),
        migrations.AddIndex(
            model_name='recepcionitem',
            index=models.Index(fields=['recepcion', 'producto'], name='facturacion_recepci_2df4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='remitointerno',
            index=models.Index(fields=['empresa', 'fecha'], name='facturacion_empresa_8a5eea_idx'),
        ),
        migrations.AddIndex(
            model_name='remitointerno',
            index=models.Index(fields=['empresa', 'sucursal_destino'], name='facturacion_empresa_cec223_idx'),
        ),
        migrations.AddIndex(
            model_name='remitointerno',
            index=models.Index(fields=['empresa', 'estado'], name='facturacion_empresa_b90147_idx'),
        ),
        migrations.AddConstraint(
            model_name='remitointerno',
            constraint=models.UniqueConstraint(fields=('empresa', 'punto', 'numero'), name='uq_remitointerno_empresa_punto_numero'),
        ),
        migrations.AddIndex(
            model_name='remitointernoitem',
            index=models.Index(fields=['remito', 'producto'], name='facturacion_remito__4c7f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcionimputacion',
            index=models.Index(fields=['orden_item'], name='facturacion_orden_i_0565d7_idx'),
        ),
        migrations.AddIndex(
            model_name='recepcionimputacion',
            index=models.Index(fields=['remito_interno_item'], name='facturacion_remito__2aaf65_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'numero'], name='facturacion_empresa_ea5842_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'proveedor'], name='facturacion_empresa_9def9d_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'fecha'], name='facturacion_empresa_903b18_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'numero'], name='facturacion_empresa_36fca8_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'cliente'], name='facturacion_empresa_c20f53_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'fecha'], name='facturacion_empresa_28f348_idx'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo', 'punto', 'numero'), name='uniq_venta_empresa_tipo_punto_numero'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['empresa', 'producto', 'fecha'], name='facturacion_empresa_c6539f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['empresa', 'sucursal', 'producto'], name='facturacion_empresa_6acb70_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['empresa', 'tipo_mov'], name='facturacion_empresa_5ca6d8_idx'),
        ),
    ]
