# Generated by Django 5.1.5 on 2026-09-14 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
        ('productos', '0003_alter_producto_unidad_venta_tomainventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='cuim',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIM'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. Serie'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='subproducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_items', to='productos.subproducto', verbose_name='Subproducto / Arma'),
        ),
    ]
