# Generated by Django 5.1.5 on 2026-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_ventaitem_cuim_ventaitem_serie_ventaitem_subproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventa',
            name='notas_sigimac',
            field=models.TextField(blank=True, null=True, verbose_name='Notas SIGIMAC (Uso Interno)'),
        ),
    ]
