# Generated by Django 5.1.5 on 2026-09-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_preventa_notas_sigimac'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteproveedor',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
    ]
