# Generated by Django 5.1.5 on 2026-09-29 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_cotizacionmoneda_dolar_cobranza_editable'),
        ('facturacion', '0005_clienteproveedor_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clienteproveedor',
            index=models.Index(fields=['empresa', 'activo', 'tipo_entidad'], name='facturacion_empresa_bfa3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='clienteproveedor',
            index=models.Index(fields=['empresa', 'activo', 'razon_social'], name='facturacion_empresa_8e8bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='clienteproveedor',
            index=models.Index(fields=['empresa', 'activo', 'cuit'], name='facturacion_empresa_30c58d_idx'),
        ),
        migrations.AddIndex(
            model_name='clienteproveedor',
            index=models.Index(fields=['empresa', 'activo', 'codigo_anterior'], name='facturacion_empresa_6ac616_idx'),
        ),
        migrations.AddIndex(
            model_name='clienteproveedor',
            index=models.Index(fields=['empresa', 'activo'], name='facturacion_empresa_903fef_idx'),
        ),
    ]
