# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_admin_sistema', models.BooleanField(default=False, verbose_name='Es Administrador de Sistema')),
                ('es_cajero_mostrador', models.BooleanField(default=False, help_text='Restringe al usuario a su caja: no ve Recibos, Órdenes de Pago ni Tesorería.', verbose_name='Sólo Caja Mostrador')),
                ('permiso_clientes_ver', models.BooleanField(default=False, verbose_name='Ver Clientes y Proveedores')),
                ('permiso_clientes_editar', models.BooleanField(default=False, verbose_name='ABM Clientes y Proveedores')),
                ('permiso_facturacion_compras', models.BooleanField(default=False, verbose_name='Módulo Compras')),
                ('permiso_facturacion_lista_compras', models.BooleanField(default=False, verbose_name='Módulo Lista de Compras')),
                ('permiso_facturacion_autorizaciones', models.BooleanField(default=False, verbose_name='Módulo Autorizaciones')),
                ('permiso_facturacion_carga_ventas', models.BooleanField(default=False, verbose_name='Módulo Carga de Ventas')),
                ('permiso_facturacion_lista_ventas', models.BooleanField(default=False, verbose_name='Módulo Lista de Ventas')),
                ('permiso_autorizar_descuentos', models.BooleanField(default=False, verbose_name='Autorizar Descuentos en Preventas')),
                ('permiso_cotizaciones_editar', models.BooleanField(default=False, verbose_name='Editar Cotizaciones de Moneda')),
                ('permiso_distribucion_asignar_stock', models.BooleanField(default=False, verbose_name='Asignar Stock Escaso (Distribución)')),
                ('permiso_distribucion_facturar_lote', models.BooleanField(default=False, verbose_name='Facturación Masiva (Distribución)')),
                ('empresas', models.ManyToManyField(blank=True, related_name='usuarios', to='empresas.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
