# Generated by Django 5.1.5 on 2026-09-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('menu_compras_carga', 'Acceso: Carga Manual de Compras'), ('menu_compras_oc', 'Acceso: Órdenes de Compra'), ('menu_compras_automatica', 'Acceso: Carga Automática (OCR)'), ('menu_compras_ia', 'Acceso: Carga por IA'), ('menu_compras_listado', 'Acceso: Listado de Compras y Facturas Pendientes'), ('menu_ventas_carga', 'Acceso: Carga de Ventas'), ('menu_ventas_listado', 'Acceso: Listado de Ventas'), ('menu_stock_dashboard', 'Acceso: Mantenimiento de Productos y Stock'), ('menu_stock_recepciones', 'Acceso: Recepción de Mercadería'), ('menu_tesoreria_caja', 'Acceso: Operar Caja Mostrador')], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
    ]
