# Generated by Django 6.0.4 on 2026-09-15 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0003_alter_perfil_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoDenegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_denegados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso Denegado',
                'verbose_name_plural': 'Permisos Denegados',
                'unique_together': {('usuario', 'permiso')},
            },
        ),
    ]
