# Generated by Django 6.0.4 on 2026-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('usuarios', '0004_permisodenegado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='sucursales',
            field=models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to='empresas.sucursal'),
        ),
    ]
