# Generated by Django 5.1.5 on 2026-09-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfil_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('menu_clientes', 'Acceso: Clientes y Proveedores'), ('menu_compras', 'Acceso: Módulo Compras (Padre)'), ('menu_compras_carga', 'Acceso: Carga Manual de Compras'), ('menu_compras_oc', 'Acceso: Órdenes de Compra'), ('menu_compras_automatica', 'Acceso: Carga Automática (OCR)'), ('menu_compras_ia', 'Acceso: Carga por IA'), ('menu_compras_listado', 'Acceso: Listado de Compras y Facturas Pendientes'), ('menu_ventas', 'Acceso: Módulo Ventas (Padre)'), ('menu_ventas_carga', 'Acceso: Carga de Ventas'), ('menu_ventas_preventas', 'Acceso: Carga de PreVentas'), ('menu_ventas_listado', 'Acceso: Listado de Ventas'), ('menu_ventas_reportes', 'Acceso: Reportes de Ventas'), ('menu_ventas_autorizaciones', 'Acceso: Lista de Autorizaciones'), ('menu_stock', 'Acceso: Módulo Stock (Padre)'), ('menu_stock_dashboard', 'Acceso: Mantenimiento de Productos y Stock'), ('menu_stock_recepciones', 'Acceso: Recepción de Mercadería'), ('menu_stock_remitos_internos', 'Acceso: Remitos Internos'), ('menu_stock_recepcion_interna', 'Acceso: Recepción Interna'), ('menu_tesoreria', 'Acceso: Módulo Tesorería (Padre)'), ('menu_tesoreria_recibos', 'Acceso: Emitir Recibo'), ('menu_tesoreria_orden_pago', 'Acceso: Emitir Orden Pago'), ('menu_tesoreria_caja', 'Acceso: Operar Caja Mostrador'), ('menu_tesoreria_caja_diaria', 'Acceso: Caja Diaria'), ('menu_tesoreria_eoaf', 'Acceso: Origen y Aplicación de Fondos'), ('menu_tesoreria_rendiciones', 'Acceso: Recepción de Rendiciones'), ('menu_contable', 'Acceso: Módulo Contable (Padre)'), ('menu_contable_libro_diario', 'Acceso: Libro Diario'), ('menu_contable_libro_mayor', 'Acceso: Libro Mayor'), ('menu_contable_balance', 'Acceso: Balance de Sumas y Saldos'), ('menu_contable_saldos', 'Acceso: Saldos Mensuales'), ('menu_impuestos', 'Acceso: Módulo Impuestos (Padre)'), ('menu_impuestos_cierre_iva', 'Acceso: Cierre Periodo IVA'), ('menu_impuestos_libro_ventas', 'Acceso: Libro IVA Ventas'), ('menu_impuestos_libro_compras', 'Acceso: Libro IVA Compras'), ('menu_impuestos_arca', 'Acceso: Captura Mis Comprobantes ARCA'), ('menu_impuestos_sicore', 'Acceso: SICORE - Retención Impuesto a las Ganancias'), ('menu_configuracion', 'Acceso: Módulo Configuración (Solo Administradores)')], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
    ]
