# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contable', '0002_initial'),
        ('empresas', '0001_initial'),
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('detalle', models.CharField(max_length=100)),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo_anterior', models.CharField(blank=True, db_index=True, help_text='ID histórico del sistema VFP para trazabilidad de migración', max_length=50, null=True, verbose_name='Código Sistema Anterior')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('detalle', models.CharField(max_length=100)),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo_anterior', models.CharField(blank=True, db_index=True, help_text='ID histórico del sistema VFP para trazabilidad de migración', max_length=50, null=True, verbose_name='Código Sistema Anterior')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('detalle', models.CharField(max_length=100)),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento Máximo Autorizado (%)')),
                ('codigo_anterior', models.CharField(blank=True, db_index=True, help_text='ID histórico del sistema VFP para trazabilidad de migración', max_length=50, null=True, verbose_name='Código Sistema Anterior')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cta_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubros_compras', to='contable.cuenta', verbose_name='Cuenta de Compras')),
                ('cta_ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubros_ventas', to='contable.cuenta', verbose_name='Cuenta de Ventas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cod_prov', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Cód. Prov')),
                ('cod_fab', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Cód. Fábrica')),
                ('detalle', models.CharField(db_index=True, max_length=255, verbose_name='Detalle del Producto')),
                ('minimo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ptopedir', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('creden', models.BooleanField(default=False)),
                ('moneda', models.CharField(choices=[('PES', 'PESO'), ('DOL', 'DOLAR'), ('60', 'EURO')], default='PES', max_length=3)),
                ('alic_iva', models.DecimalField(choices=[(Decimal('21.00'), '21%'), (Decimal('10.50'), '10.5%'), (Decimal('0.00'), '0%'), (Decimal('27.00'), '27%'), (Decimal('5.00'), '5%'), (Decimal('2.50'), '2.5%')], decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Alícuota IVA')),
                ('subprod', models.BooleanField(default=False)),
                ('peso_unitario_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Peso por Unidad de Venta (kg)')),
                ('unidad_venta', models.CharField(choices=[('UNIDAD', 'Unidad'), ('BULTO', 'Bulto / Cajón'), ('KG', 'Kilogramo')], default='UNIDAD', max_length=10, verbose_name='Unidad de Venta')),
                ('unidades_por_bulto', models.DecimalField(decimal_places=2, default=0, help_text="Cuántas unidades trae un bulto. El vendedor pide '3 cajones', no '36 unidades'.", max_digits=10, verbose_name='Unidades por Bulto')),
                ('codigo_anterior', models.CharField(blank=True, db_index=True, help_text='Código histórico del sistema anterior, utilizado para la migración.', max_length=50, null=True, verbose_name='Código Sistema Anterior')),
                ('compra_id', models.IntegerField(blank=True, null=True)),
                ('cto_adq', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fec_adq', models.DateField(blank=True, null=True)),
                ('cto_rep', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fec_act', models.DateField(blank=True, null=True)),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Margen (%)')),
                ('precio_neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cotiz_cpra', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.familia')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.marca')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_provistos', to='facturacion.clienteproveedor')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.rubro')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='familia',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familias', to='productos.rubro'),
        ),
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('stock_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Stock Inicial')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Stock Disponible (calculado)')),
                ('comprometido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Comprometido en Pedidos (calculado)')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='productos.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_productos', to='empresas.sucursal')),
            ],
            options={
                'verbose_name': 'Stock por Sucursal',
                'verbose_name_plural': 'Stocks por Sucursal',
            },
        ),
        migrations.CreateModel(
            name='Subproducto',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('subpro', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=30, verbose_name='Nro Serie / Identificador')),
                ('cuim', models.CharField(blank=True, max_length=30, null=True, verbose_name='CUIM')),
                ('feccpra', models.DateField(verbose_name='Fecha de Compra')),
                ('cto_adq', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Costo de Adquisición')),
                ('cotizadq', models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='Cotización Compra')),
                ('moneda', models.CharField(choices=[('PES', 'PESO'), ('DOL', 'DOLAR'), ('EUR', 'EURO')], default='PES', max_length=3)),
                ('alic_iva', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Alícuota IVA')),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fecvta', models.DateField(blank=True, null=True, verbose_name='Fecha de Venta')),
                ('precio_neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio Total IVA Incluido')),
                ('cotizvta', models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='Cotización Venta')),
                ('fecent', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], db_index=True, default='NUEVO', max_length=10)),
                ('propiedad', models.CharField(choices=[('PROPIA', 'Propia'), ('CONSIGNADA', 'Consignada'), ('CUSTODIA', 'Custodia')], default='PROPIA', max_length=15)),
                ('situacion', models.CharField(choices=[('DEPOSITO', 'En Depósito'), ('VENDIDA', 'Vendida')], default='DEPOSITO', max_length=15)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subproductos', to='facturacion.compra', verbose_name='Compra')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='subproductos', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproductos', to='productos.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subproductos', to='empresas.sucursal', verbose_name='Sucursal Actual')),
                ('venta', models.ForeignKey(blank=True, db_column='id_vta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproductos', to='facturacion.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Subproducto',
                'verbose_name_plural': 'Subproductos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.sucursal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'indexes': [models.Index(fields=['producto', 'sucursal', '-fecha_creacion'], name='productos_m_product_c4780e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'detalle'], name='productos_p_empresa_f95fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'cod_prov'], name='productos_p_empresa_4fad7b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'cod_fab'], name='productos_p_empresa_46aac0_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'codigo_anterior'], name='productos_p_empresa_f5174c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocksucursal',
            unique_together={('producto', 'sucursal')},
        ),
        migrations.AddIndex(
            model_name='subproducto',
            index=models.Index(fields=['empresa', 'producto'], name='productos_s_empresa_ca2295_idx'),
        ),
        migrations.AddIndex(
            model_name='subproducto',
            index=models.Index(fields=['sucursal', 'producto'], name='productos_s_sucursa_7a18fb_idx'),
        ),
        migrations.AddIndex(
            model_name='subproducto',
            index=models.Index(fields=['sucursal', 'estado'], name='productos_s_sucursa_c02903_idx'),
        ),
        migrations.AddIndex(
            model_name='subproducto',
            index=models.Index(fields=['empresa', 'serie', '-feccpra'], name='productos_s_empresa_dab509_idx'),
        ),
        migrations.AddIndex(
            model_name='subproducto',
            index=models.Index(fields=['empresa', 'cuim'], name='productos_s_empresa_9beb10_idx'),
        ),
    ]
