# Generated by Django 5.1.5 on 2026-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_venta',
            field=models.CharField(blank=True, choices=[('UNIDAD', 'Unidad'), ('BULTO', 'Bulto / Cajón'), ('KG', 'Kilogramo')], default='UNIDAD', max_length=10, verbose_name='Unidad de Venta'),
        ),
    ]
