# Generated by Django 5.1.5 on 2026-09-13 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('productos', '0002_unidad_venta_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_venta',
            field=models.CharField(blank=True, default='UNIDAD', max_length=10, verbose_name='Unidad de Venta'),
        ),
        migrations.CreateModel(
            name='TomaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField(default=1, verbose_name='N° de Inventario')),
                ('fecha_toma', models.DateTimeField(verbose_name='Fecha y Hora de la Toma')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador / En Proceso'), ('CONFIRMADO', 'Confirmado'), ('APLICADO', 'Aplicado al Stock'), ('ANULADO', 'Anulado')], db_index=True, default='BORRADOR', max_length=15, verbose_name='Estado')),
                ('terminal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Terminal / Estación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='empresas.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Toma de Inventario',
                'verbose_name_plural': 'Tomas de Inventario',
                'ordering': ['-fecha_toma', 'sucursal'],
            },
        ),
        migrations.CreateModel(
            name='TomaInventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contada', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cantidad Contada (Física)')),
                ('stock_teorico', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Stock Teórico al momento')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Diferencia (Contada - Teórico)')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Conteo')),
                ('terminal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Terminal / Estación')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.tomainventario', verbose_name='Toma de Inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_inventario', to='productos.producto', verbose_name='Producto')),
                ('usuario_conteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que contó')),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Ítems de Inventario',
            },
        ),
        migrations.AddIndex(
            model_name='tomainventario',
            index=models.Index(fields=['empresa', 'sucursal', '-fecha_toma'], name='productos_t_empresa_c18baf_idx'),
        ),
        migrations.AddIndex(
            model_name='tomainventario',
            index=models.Index(fields=['empresa', 'estado'], name='productos_t_empresa_466abd_idx'),
        ),
        migrations.AddIndex(
            model_name='tomainventarioitem',
            index=models.Index(fields=['inventario', 'producto'], name='productos_t_inventa_ffb60b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tomainventarioitem',
            unique_together={('inventario', 'producto')},
        ),
    ]
