# Generated by Django 5.1.5 on 2026-09-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_unidad_venta_tomainventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_venta',
            field=models.CharField(blank=True, default='UNIDAD', max_length=30, verbose_name='Unidad de Venta'),
        ),
    ]
