# Generated by Django 5.2.7 on 2026-09-18 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('productos', '0005_producto_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subfamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle de Subfamilia')),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Margen Sugerido (%)')),
                ('codigo_anterior', models.CharField(blank=True, db_index=True, help_text='ID histórico del sistema VFP para trazabilidad de migración', max_length=50, null=True, verbose_name='Código Sistema Anterior')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfamilias', to='productos.familia', verbose_name='Familia')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subfamilia',
                'verbose_name_plural': 'Subfamilias',
                'db_table': 'productos_subfamilia',
                'ordering': ['familia__detalle', 'detalle'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subfamilia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.subfamilia', verbose_name='Subfamilia'),
        ),
    ]
