# Generated by Django 5.1.5 on 2026-09-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_subfamilia_producto_subfamilia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones / Notas'),
        ),
    ]
