# Generated by Django 5.2.7 on 2026-09-26 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_observaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tomainventario',
            name='fecha_autorizo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Autorización'),
        ),
        migrations.AddField(
            model_name='tomainventario',
            name='filtros_aplicados',
            field=models.TextField(blank=True, null=True, verbose_name='Filtros aplicados'),
        ),
        migrations.AddField(
            model_name='tomainventario',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo / Devolución'),
        ),
        migrations.AddField(
            model_name='tomainventario',
            name='tipo_alcance',
            field=models.CharField(choices=[('GENERAL', 'Inventario General'), ('PARCIAL', 'Inventario Parcial')], default='PARCIAL', max_length=15, verbose_name='Alcance'),
        ),
        migrations.AddField(
            model_name='tomainventario',
            name='usuario_autorizo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que autorizó'),
        ),
        migrations.AddField(
            model_name='tomainventarioitem',
            name='cantidad_original_operador',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cantidad Original Operador'),
        ),
        migrations.AddField(
            model_name='tomainventarioitem',
            name='modificado_por_autorizador',
            field=models.BooleanField(default=False, verbose_name='Modificado por Autorizador'),
        ),
        migrations.AddField(
            model_name='tomainventarioitem',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='tomainventario',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador / En Conteo'), ('PENDIENTE', 'Pendiente de Autorización'), ('APLICADO', 'Aplicado al Stock'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], db_index=True, default='BORRADOR', max_length=15, verbose_name='Estado'),
        ),
    ]
