# Generated by Django 5.1.5 on 2026-09-29 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_cotizacionmoneda_dolar_cobranza_editable'),
        ('facturacion', '0006_clienteproveedor_facturacion_empresa_bfa3eb_idx_and_more'),
        ('productos', '0008_tomainventario_fecha_autorizo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familia',
            options={'ordering': ['detalle'], 'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'activo', 'detalle'], name='productos_p_empresa_52cdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'activo', 'cod_prov'], name='productos_p_empresa_689f94_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'activo', 'cod_fab'], name='productos_p_empresa_d67ade_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'activo', 'codigo_anterior'], name='productos_p_empresa_5f1b04_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'activo'], name='productos_p_empresa_264f06_idx'),
        ),
    ]
