# Generated by Django 5.1.5 on 2026-08-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad Pedida')),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad Asignada')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Ajuste de Asignación',
                'verbose_name_plural': 'Ajustes de Asignación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CarteraVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cartera de Vendedor',
                'verbose_name_plural': 'Carteras de Vendedores',
            },
        ),
        migrations.CreateModel(
            name='CobranzaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramo', models.CharField(choices=[('TRAZABLE', 'Medios con trazabilidad externa'), ('EFECTIVO', 'Efectivo'), ('MIXTO', 'Efectivo + trazables')], default='EFECTIVO', max_length=10)),
                ('excedente', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Excedente sin imputar')),
            ],
            options={
                'verbose_name': 'Cobranza de Distribucion',
                'verbose_name_plural': 'Cobranzas de Distribucion',
            },
        ),
        migrations.CreateModel(
            name='DiaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de Visita')),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL_1', 'Quincenal (1ª y 3ª semana)'), ('QUINCENAL_2', 'Quincenal (2ª y 4ª semana)')], default='SEMANAL', max_length=15)),
            ],
            options={
                'verbose_name': 'Día de Visita',
                'verbose_name_plural': 'Días de Visita',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='DomicilioEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text="Con lo que el repartidor lo identifica: 'Sucursal Centro', 'Depósito', 'Casa Central'.", max_length=100, verbose_name='Nombre del Punto')),
                ('domicilio', models.CharField(max_length=255, verbose_name='Domicilio de Entrega')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='C. Postal')),
                ('contacto', models.CharField(blank=True, max_length=150, null=True, verbose_name='A quién buscar')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_recepcion', models.CharField(blank=True, help_text="Ej. 'Hasta las 13'. Evita el viaje perdido.", max_length=100, null=True, verbose_name='Horario de Recepción')),
                ('observaciones_entrega', models.TextField(blank=True, help_text="Ej. 'Entrar por la calle lateral', 'timbre del fondo'.", null=True, verbose_name='Indicaciones de Entrega')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Domicilio de Entrega',
                'verbose_name_plural': 'Domicilios de Entrega',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionDistribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(blank=True, help_text='Agrupación del cliente para análisis y filtros.', max_length=50, null=True, verbose_name='Clasificación')),
                ('coeficiente_mayorista', models.DecimalField(decimal_places=4, default=1, help_text='Se aplica sobre el precio de lista con IVA del producto.', max_digits=10, verbose_name='Coeficiente Mayorista')),
                ('bloqueado_credito', models.BooleanField(default=False, verbose_name='Bloqueado para Crédito')),
            ],
            options={
                'verbose_name': 'Detalle Distribuidora',
                'verbose_name_plural': 'Detalles Distribuidora',
                'db_table': 'facturacion_extensiondistribuidora',
            },
        ),
        migrations.CreateModel(
            name='ExtensionPedidoDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto', models.IntegerField(help_text='Sucursal emisora del pedido (sucursal_id).', verbose_name='Punto')),
                ('numero', models.BigIntegerField(db_index=True, verbose_name='N° de Pedido')),
                ('domicilio_entrega_texto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio de Entrega (texto)')),
                ('fecha_entrega', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Entrega')),
                ('origen', models.CharField(choices=[('MOVIL', 'Móvil del vendedor'), ('PC_TELEFONICO', 'PC (pedido telefónico)'), ('PLANILLA_PAPEL', 'Planilla manual')], default='PC_TELEFONICO', max_length=20)),
                ('condic_destino', models.IntegerField(choices=[(1, 'Factura (Real)'), (2, 'PRE (Presupuestado)')], default=1, verbose_name='Se facturará como')),
                ('hora_carga', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Hora de Carga')),
                ('alerta_stock', models.BooleanField(default=False, verbose_name='Stock ajustado al tomarse')),
                ('alerta_credito', models.BooleanField(default=False, verbose_name='Fuera de límite al tomarse')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido de Distribución',
                'verbose_name_plural': 'Pedidos de Distribución',
            },
        ),
        migrations.CreateModel(
            name='MotivoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('momento', models.CharField(choices=[('PRE_CARGA', 'Antes de cargar el vehículo'), ('EN_ENTREGA', 'En la entrega al cliente'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=12, verbose_name='Momento en que aplica')),
                ('sugiere_apto_reventa', models.BooleanField(default=True, help_text='Si se desmarca, la devolución con este motivo no reingresa al stock vendible.', verbose_name='La mercadería vuelve al stock')),
                ('requiere_observacion', models.BooleanField(default=False, help_text='Para motivos genéricos, donde el dato real está en el texto libre.', verbose_name='Exige observación')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo de Devolución',
                'verbose_name_plural': 'Motivos de Devolución',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('momento', models.CharField(choices=[('PRE_CARGA', 'Antes de cargar el vehiculo'), ('EN_ENTREGA', 'En la entrega al cliente')], default='EN_ENTREGA', max_length=12)),
            ],
            options={
                'verbose_name': 'Nota de Credito de Distribucion',
                'verbose_name_plural': 'Notas de Credito de Distribucion',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.IntegerField(help_text='Código con el que se lo identifica en pantallas y reportes.', verbose_name='Código')),
                ('nombre', models.CharField(db_index=True, max_length=150, verbose_name='Nombre y Apellido')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('es_vendedor', models.BooleanField(default=False, verbose_name='Vendedor')),
                ('es_repartidor', models.BooleanField(default=False, verbose_name='Repartidor')),
                ('es_cobrador', models.BooleanField(default=False, verbose_name='Cobrador')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión (%)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha de Alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('codigo_anterior', models.CharField(blank=True, db_index=True, help_text='Código del vendedor/repartidor en el sistema anterior, para la migración.', max_length=50, null=True, verbose_name='Código Sistema Anterior')),
            ],
            options={
                'verbose_name': 'Personal de Distribución',
                'verbose_name_plural': 'Personal de Distribución',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('punto', models.IntegerField(verbose_name='Punto')),
                ('numero', models.BigIntegerField(db_index=True, verbose_name='N de Recepcion')),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Confirmada'), (2, 'Anulada')], db_index=True, default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recepcion de Devoluciones',
                'verbose_name_plural': 'Recepciones de Devoluciones',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionDevolucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad Devuelta')),
                ('apto_reventa', models.BooleanField(default=True, verbose_name='Apto para reventa')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Item de Recepcion de Devoluciones',
                'verbose_name_plural': 'Items de Recepcion de Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='RendicionReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esperado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Efectivo cobrado segun el sistema')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rendicion de Distribucion',
                'verbose_name_plural': 'Rendiciones de Distribucion',
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('punto', models.IntegerField(help_text='Sucursal emisora (sucursal_id).', verbose_name='Punto')),
                ('numero', models.BigIntegerField(db_index=True, verbose_name='N° de Reparto')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha de Salida')),
                ('estado', models.IntegerField(choices=[(0, 'Armado'), (1, 'Cerrado (salió)'), (2, 'Rendido'), (3, 'Anulado')], db_index=True, default=0)),
                ('version_impresion', models.IntegerField(default=1, verbose_name='Versión de Impresión')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reparto',
                'verbose_name_plural': 'Repartos',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='RepartoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'Entrega de mercadería'), (1, 'Sólo cobranza')], db_index=True, default=0)),
                ('domicilio_texto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio de Entrega')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Descarga')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Anterior')),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Disponible')),
                ('cobro_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cobro Mínimo')),
                ('estado_entrega', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Entregada'), (2, 'No entregada')], default=0)),
                ('observacion_repartidor', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Parada de Reparto',
                'verbose_name_plural': 'Paradas de Reparto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('patente', models.CharField(max_length=20, verbose_name='Patente')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('capacidad_kg', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Capacidad (kg)')),
                ('refrigerado', models.BooleanField(default=True, verbose_name='Refrigerado')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='ZonaReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Zona')),
                ('orden', models.IntegerField(default=0, help_text='Define la secuencia sugerida al armar el reparto.', verbose_name='Orden de Recorrido')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona de Reparto',
                'verbose_name_plural': 'Zonas de Reparto',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
