# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribucion', '0002_initial'),
        ('empresas', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('productos', '0001_initial'),
        ('tesoreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteasignacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_asignacion', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='ajusteasignacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_asignacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carteravendedor',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_entidad': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='cartera', to='facturacion.clienteproveedor', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='carteravendedor',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carteravendedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteras', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='carteravendedor',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cobranzadistribucion',
            name='recibo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion_cobranza', to='tesoreria.recibo'),
        ),
        migrations.AddField(
            model_name='diavisita',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_visita', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='domicilioentrega',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_entidad': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='domicilios_entrega', to='facturacion.clienteproveedor'),
        ),
        migrations.AddField(
            model_name='domicilioentrega',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domicilioentrega',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilios_entrega', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='domicilioentrega',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diavisita',
            name='domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_visita', to='distribucion.domicilioentrega', verbose_name='Domicilio de Entrega'),
        ),
        migrations.AddField(
            model_name='extensiondistribuidora',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribuidora', to='facturacion.clienteproveedor'),
        ),
        migrations.AddField(
            model_name='extensionpedidodistribucion',
            name='domicilio_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='distribucion.domicilioentrega', verbose_name='Domicilio de Entrega'),
        ),
        migrations.AddField(
            model_name='extensionpedidodistribucion',
            name='preventa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion', to='facturacion.preventa'),
        ),
        migrations.AddField(
            model_name='extensionpedidodistribucion',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_distribucion', to='facturacion.venta', verbose_name='Comprobante Emitido'),
        ),
        migrations.AddField(
            model_name='ajusteasignacion',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='distribucion.extensionpedidodistribucion'),
        ),
        migrations.AddField(
            model_name='motivodevolucion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motivodevolucion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos_devolucion', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='motivodevolucion',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notacreditodistribucion',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='distribucion.motivodevolucion'),
        ),
        migrations.AddField(
            model_name='notacreditodistribucion',
            name='nota_credito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion_nc', to='facturacion.venta'),
        ),
        migrations.AddField(
            model_name='notacreditodistribucion',
            name='venta_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_distribucion', to='facturacion.venta', verbose_name='Comprobante acreditado'),
        ),
        migrations.AddField(
            model_name='personal',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_distribucion', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='personal',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Sólo si la persona opera el ERP (ej. vendedor que carga pedidos desde el celular). El repartidor que trabaja con la hoja de ruta en papel no necesita usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_distribucion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema'),
        ),
        migrations.AddField(
            model_name='extensionpedidodistribucion',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Quién tomó el pedido. Es la fuente de verdad del vendedor de la operación: la venta llega a su vendedor a través del pedido.', limit_choices_to={'es_vendedor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='distribucion.personal', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='cobranzadistribucion',
            name='cobrador',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_cobrador': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobranzas', to='distribucion.personal'),
        ),
        migrations.AddField(
            model_name='carteravendedor',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'es_vendedor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='cartera', to='distribucion.personal', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='recepciondevolucion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepciondevolucion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_devolucion', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='recepciondevolucion',
            name='entregado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_repartidor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_entregadas', to='distribucion.personal', verbose_name='Entregado por (repartidor)'),
        ),
        migrations.AddField(
            model_name='recepciondevolucion',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepciondevolucion',
            name='nota_credito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepcion_devolucion', to='facturacion.venta', verbose_name='Nota de Credito emitida'),
        ),
        migrations.AddField(
            model_name='recepciondevolucion',
            name='recibido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_devolucion', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por (deposito)'),
        ),
        migrations.AddField(
            model_name='recepciondevolucion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_devolucion', to='empresas.sucursal'),
        ),
        migrations.AddField(
            model_name='notacreditodistribucion',
            name='recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='distribucion.recepciondevolucion', verbose_name='Recepcion que la origino'),
        ),
        migrations.AddField(
            model_name='recepciondevolucionitem',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_devueltos', to='distribucion.motivodevolucion'),
        ),
        migrations.AddField(
            model_name='recepciondevolucionitem',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='distribucion.recepciondevolucion'),
        ),
        migrations.AddField(
            model_name='recepciondevolucionitem',
            name='venta_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='facturacion.ventaitem'),
        ),
        migrations.AddField(
            model_name='rendicionreparto',
            name='retiro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion_rendicion', to='tesoreria.retirocaja'),
        ),
        migrations.AddField(
            model_name='rendicionreparto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rendiciones', to='distribucion.personal', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='reparto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reparto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='reparto',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reparto',
            name='responsables',
            field=models.ManyToManyField(blank=True, limit_choices_to={'es_repartidor': True}, related_name='repartos', to='distribucion.personal', verbose_name='Repartidores'),
        ),
        migrations.AddField(
            model_name='reparto',
            name='sesion_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartos', to='tesoreria.cajasesion', verbose_name='Sesion de Caja Recaudadora'),
        ),
        migrations.AddField(
            model_name='reparto',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartos', to='empresas.sucursal'),
        ),
        migrations.AddField(
            model_name='rendicionreparto',
            name='reparto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rendiciones', to='distribucion.reparto'),
        ),
        migrations.AddField(
            model_name='recepciondevolucion',
            name='reparto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='distribucion.reparto'),
        ),
        migrations.AddField(
            model_name='cobranzadistribucion',
            name='reparto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobranzas', to='distribucion.reparto'),
        ),
        migrations.AddField(
            model_name='repartoparada',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas_reparto', to='facturacion.clienteproveedor', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='repartoparada',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='distribucion.extensionpedidodistribucion', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='repartoparada',
            name='reparto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='distribucion.reparto'),
        ),
        migrations.AddField(
            model_name='repartoparada',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paradas_reparto', to='facturacion.venta', verbose_name='Comprobante'),
        ),
        migrations.AddField(
            model_name='recepciondevolucion',
            name='parada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='distribucion.repartoparada', verbose_name='Parada'),
        ),
        migrations.AddField(
            model_name='notacreditodistribucion',
            name='parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='distribucion.repartoparada'),
        ),
        migrations.AddField(
            model_name='cobranzadistribucion',
            name='parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobranzas', to='distribucion.repartoparada'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='empresas.sucursal', verbose_name='Sucursal Base'),
        ),
        migrations.AddField(
            model_name='reparto',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartos', to='distribucion.vehiculo'),
        ),
        migrations.AddField(
            model_name='zonareparto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonareparto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_reparto', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='zonareparto',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reparto',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartos', to='distribucion.zonareparto'),
        ),
        migrations.AddField(
            model_name='personal',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='distribucion.zonareparto', verbose_name='Zona Habitual'),
        ),
        migrations.AddField(
            model_name='extensionpedidodistribucion',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='distribucion.zonareparto'),
        ),
        migrations.AddField(
            model_name='domicilioentrega',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilios', to='distribucion.zonareparto', verbose_name='Zona de Reparto'),
        ),
        migrations.AddIndex(
            model_name='diavisita',
            index=models.Index(fields=['empresa', 'dia_semana'], name='distribucio_empresa_0776c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='diavisita',
            constraint=models.UniqueConstraint(fields=('domicilio', 'dia_semana'), name='uniq_diavisita_domicilio_dia'),
        ),
        migrations.AddIndex(
            model_name='ajusteasignacion',
            index=models.Index(fields=['empresa', 'fecha'], name='distribucio_empresa_4ebdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='ajusteasignacion',
            index=models.Index(fields=['producto'], name='distribucio_product_fbe3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='motivodevolucion',
            index=models.Index(fields=['empresa', 'activo'], name='distribucio_empresa_72b800_idx'),
        ),
        migrations.AddConstraint(
            model_name='motivodevolucion',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_motivo_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='carteravendedor',
            index=models.Index(fields=['empresa', 'vendedor'], name='distribucio_empresa_ad6993_idx'),
        ),
        migrations.AddConstraint(
            model_name='carteravendedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'cliente'), name='uniq_cartera_empresa_cliente'),
        ),
        migrations.AddConstraint(
            model_name='recepciondevolucionitem',
            constraint=models.UniqueConstraint(fields=('recepcion', 'venta_item'), name='uniq_recepcion_item'),
        ),
        migrations.AddIndex(
            model_name='rendicionreparto',
            index=models.Index(fields=['reparto'], name='distribucio_reparto_7167dd_idx'),
        ),
        migrations.AddIndex(
            model_name='rendicionreparto',
            index=models.Index(fields=['vendedor'], name='distribucio_vendedo_fbb2af_idx'),
        ),
        migrations.AddConstraint(
            model_name='rendicionreparto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reparto__isnull', False), ('vendedor__isnull', True)), models.Q(('reparto__isnull', True), ('vendedor__isnull', False)), _connector='OR'), name='rendicion_con_un_solo_origen'),
        ),
        migrations.AddIndex(
            model_name='repartoparada',
            index=models.Index(fields=['reparto', 'orden'], name='distribucio_reparto_0a7be8_idx'),
        ),
        migrations.AddConstraint(
            model_name='repartoparada',
            constraint=models.UniqueConstraint(condition=models.Q(('venta__isnull', False)), fields=('reparto', 'venta'), name='uniq_parada_reparto_venta'),
        ),
        migrations.AddConstraint(
            model_name='repartoparada',
            constraint=models.UniqueConstraint(condition=models.Q(('venta__isnull', False)), fields=('venta',), name='uniq_parada_venta'),
        ),
        migrations.AddConstraint(
            model_name='repartoparada',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 0), ('venta__isnull', False)), models.Q(('tipo', 1), ('venta__isnull', True)), _connector='OR'), name='parada_entrega_con_comprobante'),
        ),
        migrations.AddIndex(
            model_name='recepciondevolucion',
            index=models.Index(fields=['empresa', 'fecha'], name='distribucio_empresa_8dbdf0_idx'),
        ),
        migrations.AddIndex(
            model_name='recepciondevolucion',
            index=models.Index(fields=['reparto'], name='distribucio_reparto_2dfbf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='recepciondevolucion',
            constraint=models.UniqueConstraint(fields=('empresa', 'punto', 'numero'), name='uniq_recepcion_empresa_punto_numero'),
        ),
        migrations.AddConstraint(
            model_name='recepciondevolucion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', [0, 1])), fields=('parada',), name='uniq_recepcion_parada_vigente'),
        ),
        migrations.AddIndex(
            model_name='notacreditodistribucion',
            index=models.Index(fields=['venta_origen'], name='distribucio_venta_o_39b740_idx'),
        ),
        migrations.AddIndex(
            model_name='notacreditodistribucion',
            index=models.Index(fields=['motivo'], name='distribucio_motivo__c96c58_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranzadistribucion',
            index=models.Index(fields=['reparto'], name='distribucio_reparto_63b177_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranzadistribucion',
            index=models.Index(fields=['cobrador'], name='distribucio_cobrado_5c12b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='cobranzadistribucion',
            constraint=models.CheckConstraint(condition=models.Q(('reparto__isnull', False), ('cobrador__isnull', False), _connector='OR'), name='cobranza_con_responsable'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['empresa', 'activo'], name='distribucio_empresa_6aebcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'patente'), name='uniq_vehiculo_empresa_patente'),
        ),
        migrations.AddIndex(
            model_name='zonareparto',
            index=models.Index(fields=['empresa', 'activa'], name='distribucio_empresa_769461_idx'),
        ),
        migrations.AddConstraint(
            model_name='zonareparto',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uniq_zona_empresa_nombre'),
        ),
        migrations.AddIndex(
            model_name='reparto',
            index=models.Index(fields=['empresa', 'fecha'], name='distribucio_empresa_b2e287_idx'),
        ),
        migrations.AddIndex(
            model_name='reparto',
            index=models.Index(fields=['empresa', 'estado'], name='distribucio_empresa_ec8b5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='reparto',
            constraint=models.UniqueConstraint(fields=('empresa', 'punto', 'numero'), name='uniq_reparto_empresa_punto_numero'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['empresa', 'activo'], name='distribucio_empresa_e97ace_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['empresa', 'es_vendedor'], name='distribucio_empresa_05bfcc_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['empresa', 'es_repartidor'], name='distribucio_empresa_3b186b_idx'),
        ),
        migrations.AddConstraint(
            model_name='personal',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_personal_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='extensionpedidodistribucion',
            index=models.Index(fields=['numero'], name='distribucio_numero_f18123_idx'),
        ),
        migrations.AddIndex(
            model_name='extensionpedidodistribucion',
            index=models.Index(fields=['fecha_entrega'], name='distribucio_fecha_e_638813_idx'),
        ),
        migrations.AddIndex(
            model_name='extensionpedidodistribucion',
            index=models.Index(fields=['zona'], name='distribucio_zona_id_af7023_idx'),
        ),
        migrations.AddConstraint(
            model_name='extensionpedidodistribucion',
            constraint=models.UniqueConstraint(fields=('punto', 'numero'), name='uniq_pedido_punto_numero'),
        ),
        migrations.AddIndex(
            model_name='domicilioentrega',
            index=models.Index(fields=['empresa', 'zona'], name='distribucio_empresa_8cca68_idx'),
        ),
        migrations.AddIndex(
            model_name='domicilioentrega',
            index=models.Index(fields=['cliente', 'activo'], name='distribucio_cliente_d95c26_idx'),
        ),
        migrations.AddConstraint(
            model_name='domicilioentrega',
            constraint=models.UniqueConstraint(fields=('cliente', 'nombre'), name='uniq_domicilio_cliente_nombre'),
        ),
    ]
