# Generated by Django 5.2.7 on 2026-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='es_predeterminado',
            field=models.BooleanField(default=False, help_text='Vendedor por defecto para operaciones con clientes sin vendedor asignado.', verbose_name='Vendedor Predeterminado'),
        ),
    ]
