# Generated by Django 5.1.5 on 2026-08-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionArmeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(blank=True, choices=[('F', 'Persona Física'), ('J', 'Persona Jurídica')], max_length=1, null=True, verbose_name='Tipo de Persona')),
                ('clu', models.CharField(max_length=20, verbose_name='CLU')),
                ('clu_vto', models.DateField(blank=True, null=True, verbose_name='Vencimiento CLU')),
                ('es_policia', models.BooleanField(default=False, verbose_name='Es Policía')),
            ],
            options={
                'verbose_name': 'Detalle Armería',
                'db_table': 'facturacion_extensionarmeria',
            },
        ),
    ]
