# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armeria', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionarmeria',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='armeria', to='facturacion.clienteproveedor'),
        ),
    ]
