# Generated by Django 5.1.5 on 2026-09-04 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armeria', '0002_initial'),
        ('empresas', '0005_alter_empresa_tipo_actividad'),
        ('facturacion', '0002_initial'),
        ('productos', '0001_initial'),
        ('tesoreria', '0002_alter_cuentabancaria_banco_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_reservado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Señado / Reservado')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Total Preventa')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente Autorización SIGIMAC'), ('APLICADA', 'Aplicada en Factura de Venta'), ('DEVUELTA', 'Anulada y Devuelta (Rechazo SIGIMAC)')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado de Reserva')),
                ('fecha_reserva', models.DateField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha Resolución SIGIMAC')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_armas', to='facturacion.clienteproveedor', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_armas', to='empresas.empresa')),
                ('orden_pago_devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva_arma_devuelta', to='tesoreria.ordenpago', verbose_name='Orden de Pago Devolución')),
                ('preventa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reserva_arma', to='facturacion.preventa', verbose_name='Preventa Origen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_armas', to='productos.producto', verbose_name='Producto Reservado')),
                ('recibo_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_armas', to='tesoreria.recibo', verbose_name='Recibo de Reserva')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_armas', to='empresas.sucursal')),
                ('venta_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva_arma_aplicada', to='facturacion.venta', verbose_name='Factura de Venta Trazabilidad')),
            ],
            options={
                'verbose_name': 'Reserva de Arma (SIGIMAC)',
                'verbose_name_plural': 'Reservas de Armas (SIGIMAC)',
                'ordering': ['-fecha_reserva', '-id'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='armeria_res_empresa_f7064a_idx'), models.Index(fields=['cliente', 'estado'], name='armeria_res_cliente_f86820_idx')],
            },
        ),
    ]
