# Generated by Django 6.0.4 on 2026-09-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armeria', '0003_reservaarma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensionarmeria',
            options={'permissions': [('menu_armeria_compras', 'Acceso: Compra de Armas'), ('menu_armeria_ventas', 'Acceso: Venta Trazabilidad (Armas)'), ('menu_armeria_reservas', 'Acceso: Reservas por Venta de Armas'), ('menu_armeria_stock', 'Acceso: Stock de Armas')], 'verbose_name': 'Detalle Armería'},
        ),
    ]
