# Generated by Django 5.1.5 on 2026-09-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armeria', '0004_alter_extensionarmeria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionarmeria',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, null=True, verbose_name='Activo en Armería'),
        ),
    ]
