# Generated by Django 5.1.5 on 2026-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armeria', '0005_extensionarmeria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaarma',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Preventa'),
        ),
    ]
