# Generated by Django 5.1.5 on 2026-09-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armeria', '0006_reservaarma_notas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensionarmeria',
            options={'permissions': [('menu_armeria_compras', 'Acceso: Compra de Armas'), ('menu_armeria_ventas', 'Acceso: Venta Trazabilidad (Armas)'), ('menu_armeria_trazabilidad', 'Acceso: Trazabilidad Productos'), ('menu_armeria_reservas', 'Acceso: Reservas por Venta de Armas'), ('menu_armeria_stock', 'Acceso: Stock de Armas')], 'verbose_name': 'Detalle Armería'},
        ),
    ]
