# Generated by Django 5.1.5 on 2026-08-31 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(max_length=100, verbose_name='Nombre del Ejercicio')),
                ('inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('cierre', models.DateField(verbose_name='Fecha de Cierre')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'db_table': 'empresas_ejercicio',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaTrazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('pedir_situacion', models.BooleanField(default=False, verbose_name='Pedir Situación al comprar subproductos')),
                ('pedir_estado', models.BooleanField(default=False, verbose_name='Pedir Estado al comprar subproductos')),
                ('pedir_cuim', models.BooleanField(default=False, verbose_name='Pedir CUIM/Dominio al comprar subproductos')),
            ],
            options={
                'verbose_name': 'Configuración de Trazabilidad',
                'verbose_name_plural': 'Configuraciones de Trazabilidad',
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField(help_text='Número del punto de venta (hasta 5 dígitos)', verbose_name='Punto de Venta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('caja_mostrador_default', models.BooleanField(default=False, help_text='Si se marca, este será el punto de venta automático al facturar desde Caja Mostrador en esta sucursal.', verbose_name='Predeterminado para Caja Mostrador')),
            ],
            options={
                'verbose_name': 'Punto de Venta',
                'verbose_name_plural': 'Puntos de Venta',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Sucursal')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('punto', models.IntegerField(default=1, help_text='Número de punto de venta/emisión de la sucursal. Prenumera OC, Informes de Recepción y Remitos Internos.', verbose_name='Punto (numeración)')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='CotizacionMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('dolar_venta', models.DecimalField(decimal_places=2, default=1.0, max_digits=15, verbose_name='Dólar Venta')),
                ('dolar_cobranza', models.DecimalField(decimal_places=2, default=1.0, max_digits=15, verbose_name='Dólar Cobranza')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización Moneda',
                'verbose_name_plural': 'Cotizaciones Moneda',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('cuit', models.CharField(max_length=11, unique=True, verbose_name='CUIT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono(s)')),
                ('tipo_actividad', models.CharField(blank=True, choices=[('', 'Estándar (General)'), ('ARMERIA', 'Armería (Trazabilidad)'), ('AUTOMOTOR', 'Concesionaria Automotor (Trazabilidad)'), ('ESTUDIO', 'Estudio Contable / Abogados'), ('COLEGIO', 'Colegio / Institución Educativa'), ('DISTRIBUIDORA', 'Distribuidora'), ('AGRICOLA', 'Empresa Agrícola')], help_text='Ej: armeria, concesionaria, estudio, colegio, distribuidora, agricola', max_length=100, null=True, verbose_name='Tipo de Actividad Especial')),
                ('pedir_fecha_nacimiento_cliente', models.BooleanField(default=False, verbose_name='Pedir Fecha Nacimiento en Clientes')),
                ('usa_orden_compra', models.BooleanField(default=False, help_text='Si está activo, el circuito de compras inicia por una Orden de Compra prenumerada.', verbose_name='Usa Órdenes de Compra')),
                ('usa_trazabilidad', models.BooleanField(default=False, help_text='Si está activo, se habilita la carga y control por número de serie en compras y ventas.', verbose_name='Usa Trazabilidad de Productos')),
                ('condicion_iva', models.CharField(choices=[('RESPONSABLE INSCRIPTO', 'Responsable Inscripto'), ('MONOTRIBUTO', 'Monotributo'), ('EXENTO', 'Exento'), ('CONSUMIDOR FINAL', 'Consumidor Final')], default='CONSUMIDOR FINAL', max_length=50, verbose_name='Condición IVA')),
                ('fecha_inicio_actividades', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Actividades')),
                ('condicion_iibb', models.CharField(choices=[('LOCAL', 'Contribuyente Local'), ('CM', 'Convenio Multilateral'), ('EXENTO', 'Exento / No Inscripto')], default='LOCAL', max_length=10, verbose_name='Condición Ingresos Brutos')),
                ('entorno_afip', models.CharField(choices=[('HOMO', 'Homologación (Testing)'), ('PROD', 'Producción')], default='HOMO', max_length=4, verbose_name='Entorno ARCA (WSFEv1)')),
                ('crt_afip', models.FileField(blank=True, null=True, upload_to='certificados_afip/', verbose_name='Certificado ARCA (.crt)')),
                ('key_afip', models.FileField(blank=True, null=True, upload_to='certificados_afip/', verbose_name='Clave Privada ARCA (.key)')),
                ('vencimiento_crt_afip', models.DateField(blank=True, help_text='Fecha de expiración del certificado digital ARCA (.crt). Se autodetecta al subir el certificado.', null=True, verbose_name='Fecha de Vencimiento Certificado ARCA')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
