# Generated by Django 5.1.5 on 2026-09-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo_actividad',
            field=models.CharField(blank=True, help_text='Ej: armeria, concesionaria, estudio, colegio, distribuidora, agricola', max_length=100, null=True, verbose_name='Tipo de Actividad Especial'),
        ),
    ]
