# Generated by Django 5.1.5 on 2026-09-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_tipo_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo_actividad',
            field=models.CharField(blank=True, choices=[('', 'Estándar (General)'), ('ARMERIA', 'Armería'), ('DISTRIBUCION', 'Distribución'), ('ESTUDIO', 'Estudio Contable / Jurídico')], help_text='Filtro para habilitar funcionalidades específicas de una verticalidad.', max_length=100, null=True, verbose_name='Tipo de Actividad Especial'),
        ),
    ]
