# Generated by Django 5.1.5 on 2026-09-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_tipo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modo_edicion_facturacion',
            field=models.CharField(choices=[('DESCUENTO', 'Editar Descuento (%)'), ('PRECIO', 'Editar Precio Unitario')], default='DESCUENTO', help_text='Define si en Preventas, Ventas y Trazabilidad se edita el precio unitario directamente o el descuento porcentual.', max_length=10, verbose_name='Modo de Edición en Facturación'),
        ),
    ]
