# Generated by Django 5.2.7 on 2026-09-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionmoneda',
            name='dolar_cobranza_editable',
            field=models.BooleanField(default=True, help_text='Si está activo, el cajero u operador puede modificar la cotización puntual de la operación al cobrar; si está inactivo, la cotización es fija y solo lectura.', verbose_name='Permitir modificar Dólar Cobranza en Caja y Recibos'),
        ),
    ]
