# Generated by Django 5.1.5 on 2026-09-06 16:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contable', '0003_initial'),
        ('core_agricola', '0002_campania'),
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('facturacion', '0002_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('punto_venta', models.IntegerField(default=1, verbose_name='Punto de Venta de la Liquidación')),
                ('modo_autorizacion', models.CharField(choices=[('MANUAL', 'Manual (talonario con CAI o comprobante en línea)'), ('WEBSERVICE', 'Webservice ARCA')], default='MANUAL', max_length=12, verbose_name='Modo de autorización')),
                ('cai', models.CharField(blank=True, max_length=20, verbose_name='CAI vigente')),
                ('cai_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento del CAI')),
                ('tolerancia_pesaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diferencia admitida entre el peso declarado y el pesado en balanza.', max_digits=6, verbose_name='Tolerancia de pesaje (kg)')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_bienes_cambio', models.ForeignKey(blank=True, help_text='Cuenta patrimonial que se debita al liquidar la compra al productor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cuenta de Bienes de Cambio (Tabaco)')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_tabaco', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Acopio de Tabaco',
                'verbose_name_plural': 'Configuraciones de Acopio de Tabaco',
                'db_table': 'agricola_tabaco_configuracion',
            },
        ),
        migrations.CreateModel(
            name='VariedadTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('detalle', models.CharField(max_length=60, verbose_name='Variedad')),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variedades_tabaco', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, help_text='Producto contra el que se acumulan los kilos de esta variedad.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variedades_tabaco', to='productos.producto', verbose_name='Producto de stock')),
            ],
            options={
                'verbose_name': 'Variedad de Tabaco',
                'verbose_name_plural': 'Variedades de Tabaco',
                'db_table': 'agricola_tabaco_variedad',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecioTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('vigencia_desde', models.DateField(verbose_name='Vigente desde')),
                ('vigencia_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('moneda', models.CharField(choices=[('PES', 'Peso'), ('DOL', 'Dólar'), ('EUR', 'Euro')], default='PES', max_length=3)),
                ('precio_ponderante', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Ponderante ($/kg)')),
                ('aprobada', models.BooleanField(default=False, verbose_name='Aprobada')),
                ('aprobada_el', models.DateTimeField(blank=True, null=True, verbose_name='Aprobada el')),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por')),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_precio_tabaco', to='core_agricola.campania')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_precio_tabaco', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_precio', to='tabaco.variedadtabaco')),
            ],
            options={
                'verbose_name': 'Lista de Precio de Tabaco',
                'verbose_name_plural': 'Listas de Precio de Tabaco',
                'db_table': 'agricola_tabaco_lista_precio',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='ClaseTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('detalle', models.CharField(max_length=10, verbose_name='Clase')),
                ('grupo', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Grupo')),
                ('coeficiente', models.DecimalField(decimal_places=4, help_text='Proporción del precio ponderante. La clase índice vale 1,0000.', max_digits=6, verbose_name='Coeficiente')),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_tabaco', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='tabaco.variedadtabaco')),
            ],
            options={
                'verbose_name': 'Clase de Tabaco',
                'verbose_name_plural': 'Clases de Tabaco',
                'db_table': 'agricola_tabaco_clase',
                'ordering': ['variedad', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProductorTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo_fet', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Código FET')),
                ('finca_origen', models.CharField(blank=True, max_length=120, verbose_name='Finca / Origen')),
                ('coeficiente', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Dato de referencia del productor. NO interviene en el cálculo del precio.', max_digits=6, verbose_name='Coeficiente del productor')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado para operar')),
                ('observaciones', models.TextField(blank=True)),
                ('cliente_proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productor_tabaco', to='facturacion.clienteproveedor', verbose_name='Tercero')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productores_tabaco', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Productor de Tabaco',
                'verbose_name_plural': 'Productores de Tabaco',
                'db_table': 'agricola_tabaco_productor',
                'indexes': [models.Index(fields=['empresa', 'habilitado'], name='agricola_ta_empresa_4ef16d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipoRetencionTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=15, verbose_name='Código')),
                ('detalle', models.CharField(max_length=80, verbose_name='Concepto')),
                ('organismo', models.CharField(blank=True, max_length=80, verbose_name='Organismo recaudador')),
                ('regimen', models.CharField(blank=True, max_length=15, verbose_name='Régimen')),
                ('tipo_base', models.CharField(choices=[('NETO', 'Porcentaje sobre el neto'), ('IVA', 'Porcentaje sobre el IVA'), ('ACUM_MENSUAL', 'Acumulado mensual menos mínimo no imponible')], default='NETO', max_length=12, verbose_name='Base de cálculo')),
                ('alicuota', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Alícuota %')),
                ('minimo_no_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Mínimo no imponible')),
                ('momento', models.CharField(choices=[('LIQUIDACION', 'Al liquidar'), ('PAGO', 'Al pagar')], default='LIQUIDACION', max_length=12, verbose_name='Momento en que se practica')),
                ('solo_responsable_inscripto', models.BooleanField(default=False, help_text='La retención de IVA y la de Ganancias sólo aplican a RI.', verbose_name='Sólo a Responsables Inscriptos')),
                ('vigencia_desde', models.DateField(verbose_name='Vigente desde')),
                ('vigencia_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_contable', models.ForeignKey(help_text='Cuenta que se acredita al retener y que se cancela al depositar al organismo.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta', verbose_name='Cuenta de pasivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_tabaco', to='empresas.empresa')),
                ('jurisdiccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='facturacion.jurisdiccion')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concepto de Retención (Tabaco)',
                'verbose_name_plural': 'Conceptos de Retención (Tabaco)',
                'db_table': 'agricola_tabaco_tipo_retencion',
                'ordering': ['codigo', '-vigencia_desde'],
                'indexes': [models.Index(fields=['empresa', 'momento', 'activa'], name='agricola_ta_empresa_17b64d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('alicuota__gte', 0)), name='agro_tab_ret_alicuota_no_neg'), models.CheckConstraint(condition=models.Q(('minimo_no_imponible__gte', 0)), name='agro_tab_ret_mni_no_neg'), models.CheckConstraint(condition=models.Q(('vigencia_hasta__isnull', True), ('vigencia_hasta__gte', models.F('vigencia_desde')), _connector='OR'), name='agro_tab_ret_vigencia_coherente')],
            },
        ),
        migrations.AddConstraint(
            model_name='variedadtabaco',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='agro_tab_variedad_codigo_unico'),
        ),
        migrations.AddIndex(
            model_name='listapreciotabaco',
            index=models.Index(fields=['empresa', 'variedad', 'campania', 'vigencia_desde'], name='agricola_ta_empresa_7cfb65_idx'),
        ),
        migrations.AddConstraint(
            model_name='listapreciotabaco',
            constraint=models.CheckConstraint(condition=models.Q(('precio_ponderante__gt', 0)), name='agro_tab_lista_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='listapreciotabaco',
            constraint=models.CheckConstraint(condition=models.Q(('vigencia_hasta__isnull', True), ('vigencia_hasta__gte', models.F('vigencia_desde')), _connector='OR'), name='agro_tab_lista_vigencia_coherente'),
        ),
        migrations.AddIndex(
            model_name='clasetabaco',
            index=models.Index(fields=['empresa', 'variedad', 'activa'], name='agricola_ta_empresa_5505be_idx'),
        ),
        migrations.AddConstraint(
            model_name='clasetabaco',
            constraint=models.UniqueConstraint(fields=('empresa', 'variedad', 'codigo'), name='agro_tab_clase_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='clasetabaco',
            constraint=models.UniqueConstraint(fields=('empresa', 'variedad', 'detalle'), name='agro_tab_clase_detalle_unico'),
        ),
        migrations.AddConstraint(
            model_name='clasetabaco',
            constraint=models.CheckConstraint(condition=models.Q(('coeficiente__gt', 0)), name='agro_tab_clase_coeficiente_positivo'),
        ),
    ]
