# Generated by Django 5.1.5 on 2026-09-06 21:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agricola', '0002_campania'),
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('facturacion', '0002_initial'),
        ('tabaco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RomaneoTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('punto', models.IntegerField(default=1, verbose_name='Punto')),
                ('numero', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Número')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('ponderante_aplicado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ponderante aplicado')),
                ('coeficiente_productor', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Dato informativo del productor. NO interviene en el cálculo del precio.', max_digits=6, verbose_name='Coeficiente del productor')),
                ('transporte', models.CharField(blank=True, max_length=120, verbose_name='Transporte / Vehículo')),
                ('remito', models.CharField(blank=True, max_length=40, verbose_name='Remito o guía')),
                ('observaciones', models.TextField(blank=True)),
                ('total_kilos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_fardos', models.IntegerField(default=0)),
                ('total_importe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('adicional', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('precio_promedio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Precio promedio ponderado')),
                ('porcentaje_ponderante', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='% sobre el ponderante')),
                ('estado', models.IntegerField(choices=[(1, 'Borrador'), (2, 'Confirmado'), (3, 'Liquidado'), (9, 'Anulado')], db_index=True, default=1)),
                ('condic', models.IntegerField(default=1, verbose_name='Condición')),
                ('motivo_anulacion', models.CharField(blank=True, max_length=200)),
                ('anulado_el', models.DateTimeField(blank=True, null=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos_tabaco', to='core_agricola.campania')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos_tabaco', to='empresas.empresa')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos', to='tabaco.listapreciotabaco', verbose_name='Lista aplicada')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos_tabaco', to='facturacion.clienteproveedor', verbose_name='Productor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos_tabaco', to='empresas.sucursal')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos', to='tabaco.variedadtabaco')),
            ],
            options={
                'verbose_name': 'Romaneo de Tabaco',
                'verbose_name_plural': 'Romaneos de Tabaco',
                'db_table': 'agricola_tabaco_romaneo',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='FardoTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_fardo', models.IntegerField(verbose_name='Nro de fardo')),
                ('etiqueta', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Etiqueta / código de barras')),
                ('coeficiente_aplicado', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Coeficiente aplicado')),
                ('precio_aplicado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario aplicado')),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kilos')),
                ('importe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('adicional', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('precio_final', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Precio final (con adicional)')),
                ('estado', models.IntegerField(choices=[(1, 'Recibido'), (2, 'Clasificado'), (3, 'En lote de acopio'), (4, 'Acondicionado'), (5, 'Vendido')], db_index=True, default=2)),
                ('clasificado_el', models.DateTimeField(blank=True, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fardos', to='tabaco.clasetabaco')),
                ('clasificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('romaneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fardos', to='tabaco.romaneotabaco')),
            ],
            options={
                'verbose_name': 'Fardo de Tabaco',
                'verbose_name_plural': 'Fardos de Tabaco',
                'db_table': 'agricola_tabaco_fardo',
                'ordering': ['romaneo', 'numero_fardo'],
            },
        ),
        migrations.CreateModel(
            name='ReclasificacionFardo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente_anterior', models.DecimalField(decimal_places=4, max_digits=6)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coeficiente_nuevo', models.DecimalField(decimal_places=4, max_digits=6)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe_nuevo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clase_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tabaco.clasetabaco')),
                ('clase_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tabaco.clasetabaco')),
                ('fardo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclasificaciones', to='tabaco.fardotabaco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclasificación de Fardo',
                'verbose_name_plural': 'Reclasificaciones de Fardos',
                'db_table': 'agricola_tabaco_reclasificacion',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fardo', '-fecha'], name='agricola_ta_fardo_i_3e07ed_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='romaneotabaco',
            index=models.Index(fields=['empresa', 'estado', '-fecha'], name='agricola_ta_empresa_168fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='romaneotabaco',
            index=models.Index(fields=['empresa', 'productor', '-fecha'], name='agricola_ta_empresa_17eeeb_idx'),
        ),
        migrations.AddIndex(
            model_name='romaneotabaco',
            index=models.Index(fields=['empresa', 'campania', 'variedad'], name='agricola_ta_empresa_4ef93f_idx'),
        ),
        migrations.AddConstraint(
            model_name='romaneotabaco',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('empresa', 'punto', 'numero'), name='agro_tab_romaneo_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='romaneotabaco',
            constraint=models.CheckConstraint(condition=models.Q(('total_kilos__gte', 0)), name='agro_tab_romaneo_kilos_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='romaneotabaco',
            constraint=models.CheckConstraint(condition=models.Q(('total_fardos__gte', 0)), name='agro_tab_romaneo_fardos_no_neg'),
        ),
        migrations.AddIndex(
            model_name='fardotabaco',
            index=models.Index(fields=['romaneo', 'clase'], name='agricola_ta_romaneo_44c131_idx'),
        ),
        migrations.AddIndex(
            model_name='fardotabaco',
            index=models.Index(fields=['estado'], name='agricola_ta_estado_e2d88b_idx'),
        ),
        migrations.AddConstraint(
            model_name='fardotabaco',
            constraint=models.UniqueConstraint(fields=('romaneo', 'numero_fardo'), name='agro_tab_fardo_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='fardotabaco',
            constraint=models.CheckConstraint(condition=models.Q(('kilos__gt', 0)), name='agro_tab_fardo_kilos_positivos'),
        ),
        migrations.AddConstraint(
            model_name='fardotabaco',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='agro_tab_fardo_importe_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='fardotabaco',
            constraint=models.CheckConstraint(condition=models.Q(('coeficiente_aplicado__gt', 0)), name='agro_tab_fardo_coeficiente_positivo'),
        ),
    ]
