# Generated by Django 5.1.5 on 2026-09-07 00:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0003_initial'),
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('facturacion', '0002_initial'),
        ('tabaco', '0002_romaneotabaco_fardotabaco_reclasificacionfardo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontabaco',
            name='alicuota_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Se aplica al liquidar a productores Responsables Inscriptos.', max_digits=6, verbose_name='Alícuota de IVA (%)'),
        ),
        migrations.CreateModel(
            name='LiquidacionTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('codiva', models.CharField(default='150', max_length=3, verbose_name='Cód. Comprobante ARCA')),
                ('punto', models.IntegerField(default=1, verbose_name='Punto de Venta')),
                ('numero', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Número')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('periodo', models.CharField(blank=True, db_index=True, max_length=6, verbose_name='Período YYYYMM')),
                ('origen_autorizacion', models.CharField(choices=[('MANUAL', 'Manual (talonario con CAI o comprobante en línea)'), ('WEBSERVICE', 'Webservice ARCA')], default='MANUAL', max_length=12)),
                ('cai', models.CharField(blank=True, max_length=20, verbose_name='CAI')),
                ('cae', models.CharField(blank=True, max_length=20, verbose_name='CAE')),
                ('vencimiento_autorizacion', models.DateField(blank=True, null=True, verbose_name='Vto. CAI/CAE')),
                ('neto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('alicuota_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Alícuota IVA aplicada')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('retenciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Retenciones practicadas al liquidar')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='neto + IVA − retenciones de liquidación. Es lo que suma la cuenta corriente y lo que cancela la Orden de Pago; NO es el neto a pagar, porque Ganancias se retiene recién al pagar.', max_digits=15, verbose_name='Total (deuda con el productor)')),
                ('pagado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('asiento_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Asiento Contable')),
                ('condic', models.IntegerField(default=1, verbose_name='Condición')),
                ('estado', models.IntegerField(choices=[(1, 'Borrador'), (2, 'Confirmada'), (9, 'Anulada')], db_index=True, default=1)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=200)),
                ('anulada_el', models.DateTimeField(blank=True, null=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_tabaco', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_tabaco', to='facturacion.clienteproveedor', verbose_name='Productor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_tabaco', to='empresas.sucursal')),
            ],
            options={
                'verbose_name': 'Liquidación de Compra de Tabaco',
                'verbose_name_plural': 'Liquidaciones de Compra de Tabaco',
                'db_table': 'agricola_tabaco_liquidacion',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('detalle', models.CharField(max_length=80)),
                ('tipo_base', models.CharField(max_length=12)),
                ('alicuota', models.DecimalField(decimal_places=4, max_digits=7)),
                ('minimo_no_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('base', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base sobre la que se calculó')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nro_certificado', models.CharField(blank=True, max_length=30, verbose_name='Nro. Certificado')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta')),
                ('tipo_retencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tabaco.tiporetenciontabaco')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones_aplicadas', to='tabaco.liquidaciontabaco')),
            ],
            options={
                'verbose_name': 'Retención de Liquidación',
                'verbose_name_plural': 'Retenciones de Liquidación',
                'db_table': 'agricola_tabaco_liquidacion_retencion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fardos', models.IntegerField(default=0)),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coeficiente', models.DecimalField(decimal_places=4, max_digits=6)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tabaco.clasetabaco')),
                ('romaneo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_liquidacion', to='tabaco.romaneotabaco')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tabaco.liquidaciontabaco')),
            ],
            options={
                'verbose_name': 'Detalle de Liquidación',
                'verbose_name_plural': 'Detalles de Liquidación',
                'db_table': 'agricola_tabaco_liquidacion_detalle',
                'ordering': ['romaneo', 'clase'],
            },
        ),
        migrations.AddField(
            model_name='romaneotabaco',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='romaneos', to='tabaco.liquidaciontabaco', verbose_name='Liquidación'),
        ),
        migrations.AddIndex(
            model_name='liquidaciontabaco',
            index=models.Index(fields=['empresa', 'estado', '-fecha'], name='agricola_ta_empresa_4af1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidaciontabaco',
            index=models.Index(fields=['empresa', 'productor', '-fecha'], name='agricola_ta_empresa_e3caf2_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidaciontabaco',
            index=models.Index(fields=['empresa', 'periodo'], name='agricola_ta_empresa_190c99_idx'),
        ),
        migrations.AddConstraint(
            model_name='liquidaciontabaco',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('empresa', 'letra', 'punto', 'numero'), name='agro_tab_liq_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='liquidaciontabaco',
            constraint=models.CheckConstraint(condition=models.Q(('neto__gte', 0)), name='agro_tab_liq_neto_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='liquidaciontabaco',
            constraint=models.CheckConstraint(condition=models.Q(('iva__gte', 0)), name='agro_tab_liq_iva_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='liquidaciontabaco',
            constraint=models.CheckConstraint(condition=models.Q(('retenciones__gte', 0)), name='agro_tab_liq_ret_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionretencion',
            constraint=models.UniqueConstraint(fields=('liquidacion', 'tipo_retencion'), name='agro_tab_liqret_unica'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionretencion',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='agro_tab_liqret_importe_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='liquidaciondetalle',
            constraint=models.UniqueConstraint(fields=('liquidacion', 'romaneo', 'clase'), name='agro_tab_liqdet_unico'),
        ),
        migrations.AddConstraint(
            model_name='liquidaciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('kilos__gt', 0)), name='agro_tab_liqdet_kilos_positivos'),
        ),
    ]
