# Generated by Django 5.1.5 on 2026-09-07 13:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0003_initial'),
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('facturacion', '0002_initial'),
        ('tabaco', '0003_liquidacion'),
        ('tesoreria', '0002_alter_cuentabancaria_banco_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('anulado', models.BooleanField(db_index=True, default=False)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='tabaco.liquidaciontabaco')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_liquidacion_tabaco', to='tesoreria.ordenpago')),
            ],
            options={
                'verbose_name': 'Imputación de Pago a Liquidación',
                'verbose_name_plural': 'Imputaciones de Pago a Liquidaciones',
                'db_table': 'agricola_tabaco_liquidacion_pago',
                'indexes': [models.Index(fields=['liquidacion', 'anulado'], name='agricola_ta_liquida_ed95f6_idx'), models.Index(fields=['orden_pago'], name='agricola_ta_orden_p_23a74d_idx')],
                'constraints': [models.UniqueConstraint(fields=('liquidacion', 'orden_pago'), name='agro_tab_liqpago_unico')],
            },
        ),
        migrations.CreateModel(
            name='RetencionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('detalle', models.CharField(max_length=80)),
                ('regimen', models.CharField(blank=True, max_length=15)),
                ('alicuota', models.DecimalField(decimal_places=4, max_digits=7)),
                ('minimo_no_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('periodo', models.CharField(db_index=True, max_length=6, verbose_name='Período YYYYMM')),
                ('base_del_pago', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Neto liquidado en este pago')),
                ('base_acumulada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Neto acumulado del mes')),
                ('retencion_del_mes', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Retención total del mes')),
                ('retenido_previo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Ya retenido en el mes')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Importe retenido ahora')),
                ('nro_certificado', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Nro. Certificado')),
                ('fecha', models.DateField(db_index=True)),
                ('anulado', models.BooleanField(db_index=True, default=False)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contable.cuenta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_pago_tabaco', to='empresas.empresa')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_tabaco', to='tesoreria.ordenpago')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_tabaco', to='facturacion.clienteproveedor')),
                ('tipo_retencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tabaco.tiporetenciontabaco')),
            ],
            options={
                'verbose_name': 'Retención Practicada en el Pago',
                'verbose_name_plural': 'Retenciones Practicadas en el Pago',
                'db_table': 'agricola_tabaco_retencion_pago',
                'ordering': ['-fecha', '-nro_certificado'],
                'indexes': [models.Index(fields=['empresa', 'productor', 'periodo', 'anulado'], name='agricola_ta_empresa_e44e2e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('nro_certificado__isnull', False)), fields=('empresa', 'nro_certificado'), name='agro_tab_retpago_certificado_unico'), models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='agro_tab_retpago_importe_no_neg')],
            },
        ),
    ]
