# Generated by Django 5.1.5 on 2026-09-07 17:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agricola', '0002_campania'),
        ('empresas', '0006_empresa_modo_edicion_facturacion'),
        ('facturacion', '0002_initial'),
        ('productos', '0002_unidad_venta_opcional'),
        ('tabaco', '0004_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoAcondicionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=12, verbose_name='Código')),
                ('detalle', models.CharField(max_length=120, verbose_name='Detalle')),
                ('merma_normal_porcentaje', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Merma esperada del proceso. Lo que la exceda se marca como extraordinaria.', max_digits=6, verbose_name='% de merma normal')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proceso de Acondicionamiento',
                'verbose_name_plural': 'Procesos de Acondicionamiento',
                'db_table': 'agricola_tabaco_proceso_acond',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Acondicionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField(default=1, verbose_name='Nro')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('kilos_entrada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kilos de entrada')),
                ('kilos_salida', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kilos de salida')),
                ('kilos_coproductos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('kilos_baja', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Entrada menos salida. Es lo que el término de stock resta de la variedad.', max_digits=15, verbose_name='Kilos dados de baja')),
                ('kilos_merma', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Merma')),
                ('merma_normal_esperada', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('merma_extraordinaria', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('porcentaje_merma_normal_aplicado', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('valor_coproductos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('motivo_merma', models.CharField(blank=True, max_length=200, verbose_name='Motivo de la merma extraordinaria')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.IntegerField(choices=[(1, 'Borrador'), (2, 'Cerrado'), (9, 'Anulado')], db_index=True, default=1)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=200)),
                ('anulado_el', models.DateTimeField(blank=True, null=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acondicionamiento',
                'verbose_name_plural': 'Acondicionamientos',
                'db_table': 'agricola_tabaco_acondicionamiento',
                'ordering': ['lote', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AcondicionamientoCoproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kilos')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Valor estimado')),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('acondicionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coproductos', to='tabaco.acondicionamiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coproductos_tabaco', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Coproducto de Acondicionamiento',
                'verbose_name_plural': 'Coproductos de Acondicionamiento',
                'db_table': 'agricola_tabaco_acond_coproducto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AcondicionamientoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=160, verbose_name='Concepto')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Importe')),
                ('acondicionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='tabaco.acondicionamiento')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_acondicionamiento', to='facturacion.compra', verbose_name='Compra de respaldo')),
            ],
            options={
                'verbose_name': 'Costo de Acondicionamiento',
                'verbose_name_plural': 'Costos de Acondicionamiento',
                'db_table': 'agricola_tabaco_acond_costo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LoteAcopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('punto', models.IntegerField(default=1, verbose_name='Punto')),
                ('numero', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Número')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(blank=True, max_length=160, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.IntegerField(choices=[(1, 'Borrador'), (2, 'Armado'), (3, 'Acondicionado'), (4, 'Vendido'), (9, 'Anulado')], db_index=True, default=1)),
                ('total_fardos', models.IntegerField(default=0)),
                ('total_kilos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Kilos de compra')),
                ('kilos_actuales', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Kilos de compra menos las bajas de acondicionamiento.', max_digits=15, verbose_name='Kilos actuales')),
                ('costo_compra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Costo de compra')),
                ('costo_acondicionamiento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Costo de acondicionamiento')),
                ('valor_coproductos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Valor de coproductos')),
                ('importe_venta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Importe de venta')),
                ('motivo_anulacion', models.CharField(blank=True, max_length=200)),
                ('anulado_el', models.DateTimeField(blank=True, null=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_tabaco', to='core_agricola.campania')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_tabaco', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_tabaco', to='empresas.sucursal')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='tabaco.variedadtabaco')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_tabaco', to='facturacion.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Lote de Acopio',
                'verbose_name_plural': 'Lotes de Acopio',
                'db_table': 'agricola_tabaco_lote',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.AddField(
            model_name='acondicionamiento',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acondicionamientos', to='tabaco.loteacopio'),
        ),
        migrations.AddField(
            model_name='fardotabaco',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fardos', to='tabaco.loteacopio', verbose_name='Lote de acopio'),
        ),
        migrations.AddIndex(
            model_name='fardotabaco',
            index=models.Index(fields=['lote', 'estado'], name='agricola_ta_lote_id_25ad1b_idx'),
        ),
        migrations.AddField(
            model_name='procesoacondicionamiento',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procesoacondicionamiento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_acondicionamiento', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='procesoacondicionamiento',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acondicionamiento',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acondicionamientos', to='tabaco.procesoacondicionamiento'),
        ),
        migrations.AddIndex(
            model_name='acondicionamientocoproducto',
            index=models.Index(fields=['acondicionamiento'], name='agricola_ta_acondic_5c40bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='acondicionamientocoproducto',
            constraint=models.UniqueConstraint(fields=('acondicionamiento', 'producto'), name='agro_tab_coproducto_unico'),
        ),
        migrations.AddConstraint(
            model_name='acondicionamientocoproducto',
            constraint=models.CheckConstraint(condition=models.Q(('kilos__gt', 0)), name='agro_tab_coproducto_kilos_positivos'),
        ),
        migrations.AddConstraint(
            model_name='acondicionamientocoproducto',
            constraint=models.CheckConstraint(condition=models.Q(('valor_estimado__gte', 0)), name='agro_tab_coproducto_valor_no_neg'),
        ),
        migrations.AddIndex(
            model_name='acondicionamientocosto',
            index=models.Index(fields=['acondicionamiento'], name='agricola_ta_acondic_8cfc2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='acondicionamientocosto',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='agro_tab_acond_costo_no_neg'),
        ),
        migrations.AddIndex(
            model_name='loteacopio',
            index=models.Index(fields=['empresa', 'estado', '-fecha'], name='agricola_ta_empresa_8b7fed_idx'),
        ),
        migrations.AddIndex(
            model_name='loteacopio',
            index=models.Index(fields=['empresa', 'campania', 'variedad'], name='agricola_ta_empresa_55ed8a_idx'),
        ),
        migrations.AddIndex(
            model_name='loteacopio',
            index=models.Index(fields=['empresa', 'sucursal', 'estado'], name='agricola_ta_empresa_93a2f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='loteacopio',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('empresa', 'punto', 'numero'), name='agro_tab_lote_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='loteacopio',
            constraint=models.CheckConstraint(condition=models.Q(('total_kilos__gte', 0)), name='agro_tab_lote_kilos_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='loteacopio',
            constraint=models.CheckConstraint(condition=models.Q(('total_fardos__gte', 0)), name='agro_tab_lote_fardos_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='loteacopio',
            constraint=models.CheckConstraint(condition=models.Q(('costo_compra__gte', 0)), name='agro_tab_lote_costo_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='procesoacondicionamiento',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='agro_tab_proceso_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='procesoacondicionamiento',
            constraint=models.CheckConstraint(condition=models.Q(('merma_normal_porcentaje__gte', 0), ('merma_normal_porcentaje__lte', 100)), name='agro_tab_proceso_merma_0_100'),
        ),
        migrations.AddIndex(
            model_name='acondicionamiento',
            index=models.Index(fields=['lote', 'estado'], name='agricola_ta_lote_id_4147eb_idx'),
        ),
        migrations.AddIndex(
            model_name='acondicionamiento',
            index=models.Index(fields=['estado', '-fecha'], name='agricola_ta_estado_ca2ecd_idx'),
        ),
        migrations.AddConstraint(
            model_name='acondicionamiento',
            constraint=models.UniqueConstraint(fields=('lote', 'numero'), name='agro_tab_acond_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='acondicionamiento',
            constraint=models.CheckConstraint(condition=models.Q(('kilos_entrada__gt', 0)), name='agro_tab_acond_entrada_positiva'),
        ),
        migrations.AddConstraint(
            model_name='acondicionamiento',
            constraint=models.CheckConstraint(condition=models.Q(('kilos_salida__gte', 0)), name='agro_tab_acond_salida_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='acondicionamiento',
            constraint=models.CheckConstraint(condition=models.Q(('kilos_salida__lte', models.F('kilos_entrada'))), name='agro_tab_acond_salida_menor_entrada'),
        ),
    ]
