# Generated by Django 5.1.5 on 2026-09-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabaco', '0005_etapa5_lotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporetenciontabaco',
            name='columna_fet',
            field=models.CharField(blank=True, choices=[('ret_iva', 'Ret. IVA'), ('ret_ganancias', 'Ret. Ganancias'), ('ret_eeaoc', 'EEAOC'), ('ret_salud', 'Salud Pública'), ('ret_agua', 'Uso de Agua')], help_text='A qué columna del informe FET aporta. Vacío = «Otras retenciones».', max_length=15, verbose_name='Columna en la planilla FET'),
        ),
    ]
